Repository milvus-io/milvus-sdk-java, pull requests merged in 2021-12, with the labels that each got.

#230 Java API Reference Revision
  src/main/java/io/milvus/Response/FieldDataWrapper.java
  src/main/java/io/milvus/Response/GetCollStatResponseWrapper.java
  src/main/java/io/milvus/Response/InsertResultWrapper.java
  src/main/java/io/milvus/Response/QueryResultsWrapper.java
  src/main/java/io/milvus/Response/SearchResultsWrapper.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/exception/ClientNotConnectedException.java
  src/main/java/io/milvus/exception/IllegalResponseException.java
  src/main/java/io/milvus/exception/ParamException.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/IndexType.java
  src/main/java/io/milvus/param/MetricType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/R.java
  src/main/java/io/milvus/param/RpcStatus.java
  src/main/java/io/milvus/param/alias/AlterAliasParam.java
  src/main/java/io/milvus/param/alias/CreateAliasParam.java
  src/main/java/io/milvus/param/alias/DropAliasParam.java
  src/main/java/io/milvus/param/collection/CreateCollectionParam.java
  src/main/java/io/milvus/param/collection/DescribeCollectionParam.java
  src/main/java/io/milvus/param/collection/DropCollectionParam.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/collection/FlushParam.java
  src/main/java/io/milvus/param/collection/GetCollectionStatisticsParam.java
  src/main/java/io/milvus/param/collection/HasCollectionParam.java
  src/main/java/io/milvus/param/collection/LoadCollectionParam.java
  src/main/java/io/milvus/param/collection/ReleaseCollectionParam.java
  src/main/java/io/milvus/param/collection/ShowCollectionsParam.java
  src/main/java/io/milvus/param/control/GetCompactionPlansParam.java
  src/main/java/io/milvus/param/control/GetCompactionStateParam.java
  src/main/java/io/milvus/param/control/GetMetricsParam.java
  src/main/java/io/milvus/param/control/GetPersistentSegmentInfoParam.java
  src/main/java/io/milvus/param/control/GetQuerySegmentInfoParam.java
  src/main/java/io/milvus/param/control/LoadBalanceParam.java
  src/main/java/io/milvus/param/control/ManualCompactionParam.java
  src/main/java/io/milvus/param/dml/CalcDistanceParam.java
  src/main/java/io/milvus/param/dml/DeleteParam.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
  src/main/java/io/milvus/param/index/DescribeIndexParam.java
  src/main/java/io/milvus/param/index/DropIndexParam.java
  src/main/java/io/milvus/param/index/GetIndexBuildProgressParam.java
  src/main/java/io/milvus/param/index/GetIndexStateParam.java
  src/main/java/io/milvus/param/partition/CreatePartitionParam.java
  src/main/java/io/milvus/param/partition/DropPartitionParam.java
  src/main/java/io/milvus/param/partition/GetPartitionStatisticsParam.java
  src/main/java/io/milvus/param/partition/HasPartitionParam.java
  src/main/java/io/milvus/param/partition/LoadPartitionsParam.java
  src/main/java/io/milvus/param/partition/ReleasePartitionsParam.java
  src/main/java/io/milvus/param/partition/ShowPartitionsParam.java
Labels: lgtm, approved, ci-passed, size/XL

#231 Add wrapper for DescribeCollectionResponse
  examples/main/io/milvus/GeneralExample.java
  src/main/java/io/milvus/Response/DescCollResponseWrapper.java
  src/main/java/io/milvus/param/collection/CreateCollectionParam.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#232 Add more wrappers
  examples/main/io/milvus/GeneralExample.java
  src/main/java/io/milvus/Response/DescCollResponseWrapper.java
  src/main/java/io/milvus/Response/DescIndexResponseWrapper.java
  src/main/java/io/milvus/Response/GetPartStatResponseWrapper.java
  src/main/java/io/milvus/Response/MutationResultWrapper.java
  src/main/java/io/milvus/Response/ShowCollResponseWrapper.java
  src/main/java/io/milvus/Response/ShowPartResponseWrapper.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/partition/GetPartitionStatisticsParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#233 Rename some methods to lower case
  examples/main/io/milvus/GeneralExample.java
  src/main/java/io/milvus/Response/DescCollResponseWrapper.java
  src/main/java/io/milvus/Response/DescIndexResponseWrapper.java
  src/main/java/io/milvus/Response/GetCollStatResponseWrapper.java
  src/main/java/io/milvus/Response/GetPartStatResponseWrapper.java
  src/main/java/io/milvus/Response/SearchResultsWrapper.java
  src/main/java/io/milvus/Response/ShowCollResponseWrapper.java
  src/main/java/io/milvus/Response/ShowPartResponseWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed

#234 Add unittest cases
  src/main/java/io/milvus/Response/GetCollStatResponseWrapper.java
  src/main/java/io/milvus/Response/GetPartStatResponseWrapper.java
  src/main/java/io/milvus/Response/ShowCollResponseWrapper.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#235 Add unittest cases
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#236 Improve code coverage
  src/main/java/io/milvus/Response/SearchResultsWrapper.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/XS

#237 Upgrade log4j to 2.15.0
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#239 #238 Upgrade log4j version to 2.15.0 for high severity vulnerability
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#240 Fix bug of SearchResultsWrapper
  examples/main/io/milvus/GeneralExample.java
  src/main/java/io/milvus/Response/DescCollResponseWrapper.java
  src/main/java/io/milvus/Response/DescIndexResponseWrapper.java
  src/main/java/io/milvus/Response/QueryResultsWrapper.java
  src/main/java/io/milvus/Response/SearchResultsWrapper.java
  src/main/java/io/milvus/Response/ShowCollResponseWrapper.java
  src/main/java/io/milvus/Response/ShowPartResponseWrapper.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#241 Modify ManualCompact interface
  examples/main/io/milvus/GeneralExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/param/control/ManualCompactionParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#242 Add timeout setting for rpc call
  examples/main/io/milvus/GeneralExample.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#243 Implement getFlushState()
  examples/main/io/milvus/GeneralExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/param/control/GetFlushStateParam.java
  src/main/proto/common.proto
  src/main/proto/milvus.proto
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  src/test/java/io/milvus/server/MockMilvusServerImpl.java
Labels: size/L, lgtm, approved, ci-passed

#244 Fix typo
  src/main/java/io/milvus/Response/FieldDataWrapper.java
  src/main/java/io/milvus/param/collection/CreateCollectionParam.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/collection/FlushParam.java
  src/main/java/io/milvus/param/control/ManualCompactionParam.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
  src/main/java/io/milvus/param/partition/ShowPartitionsParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed
