Repository milvus-io/milvus-sdk-java, pull requests merged in 2021-11, with the labels that each got.

#214 Add mock server for unittest
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/R.java
  src/main/java/io/milvus/param/collection/CreateCollectionParam.java
  src/test/java/io/milvus/client/MilvusClientTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  src/test/java/io/milvus/server/MockMilvusServer.java
  src/test/java/io/milvus/server/MockMilvusServerImpl.java
Labels: enhancement, size/L, lgtm, approved, ci-passed

#212 Add workflow to generate javadoc
  .github/workflows/generate_javadoc.yml
Labels: lgtm, size/S

#217 Update proto
  src/main/proto/common.proto
  src/main/proto/milvus.proto
Labels: size/L

#216 Add code review.md
  CODE_REVIEW.md
Labels: documentation, lgtm, approved, ci-passed, size/M

#223 Fix mergify
  .github/mergify.yml
  OWNERS
Labels: lgtm, approved, ci-passed, size/XS

#224 Change README
  .github/mergify.yml
  README.md
  examples/pom.xml
Labels: lgtm, approved, ci-passed, size/S

#225 Fix some problems
  .github/mergify.yml
  .github/workflows/maven.yml
  examples/main/io/milvus/GeneralExample.java
  src/main/java/io/milvus/Response/FieldDataWrapper.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/XL

#226 Update proto
  src/main/proto/common.proto
  src/main/proto/milvus.proto
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/XL

#227 Fix typo
  src/main/java/io/milvus/Response/FieldDataWrapper.java
  src/main/java/io/milvus/Response/GetCollStatResponseWrapper.java
  src/main/java/io/milvus/Response/QueryResultsWrapper.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/collection/FlushParam.java
  src/main/java/io/milvus/param/collection/LoadCollectionParam.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
  src/main/java/io/milvus/param/partition/LoadPartitionsParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#228 Example for two vector fields
  examples/main/io/milvus/GeneralExample.java
Labels: size/L, lgtm, approved, ci-passed

#229 Implement new interfaces
  src/main/java/io/milvus/Response/FieldDataWrapper.java
  src/main/java/io/milvus/Response/SearchResultsWrapper.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/RpcStatus.java
  src/main/java/io/milvus/param/collection/CreateCollectionParam.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/collection/FlushParam.java
  src/main/java/io/milvus/param/collection/ShowCollectionsParam.java
  src/main/java/io/milvus/param/control/GetCompactionPlansParam.java
  src/main/java/io/milvus/param/control/GetCompactionStateParam.java
  src/main/java/io/milvus/param/control/LoadBalanceParam.java
  src/main/java/io/milvus/param/control/ManualCompactionParam.java
  src/main/java/io/milvus/param/partition/LoadPartitionsParam.java
  src/main/java/io/milvus/param/partition/ReleasePartitionsParam.java
  src/main/java/io/milvus/param/partition/ShowPartitionsParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  src/test/java/io/milvus/server/MockMilvusServerImpl.java
Labels: lgtm, size/XXL, approved, ci-passed
