Repository milvus-io/milvus-sdk-java, pull requests merged in 2021-08, with the labels that each got.

#190 Change master branch to Milvus 2.0, bring in protos
  examples/src/main/java/MilvusClientExample.java
  pom.xml
  src/main/java/io/milvus/client/CollectionMapping.java
  src/main/java/io/milvus/client/ConnectFailedException.java
  src/main/java/io/milvus/client/ConnectParam.java
  src/main/java/io/milvus/client/CountEntitiesResponse.java
  src/main/java/io/milvus/client/GetCollectionInfoResponse.java
  src/main/java/io/milvus/client/GetEntityByIDResponse.java
  src/main/java/io/milvus/client/GetIndexInfoResponse.java
  src/main/java/io/milvus/client/HasCollectionResponse.java
  src/main/java/io/milvus/client/HasPartitionResponse.java
  src/main/java/io/milvus/client/Index.java
  src/main/java/io/milvus/client/IndexType.java
  src/main/java/io/milvus/client/InsertParam.java
  src/main/java/io/milvus/client/InsertResponse.java
  src/main/java/io/milvus/client/ListCollectionsResponse.java
  src/main/java/io/milvus/client/ListIDInSegmentResponse.java
  src/main/java/io/milvus/client/ListPartitionsResponse.java
  src/main/java/io/milvus/client/MetricType.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusGrpcClient.java
  src/main/java/io/milvus/client/Response.java
  src/main/java/io/milvus/client/SearchParam.java
  src/main/java/io/milvus/client/SearchResponse.java
  src/main/java/io/milvus/client/exception/InitializationException.java
  src/main/java/io/milvus/client/exception/MilvusException.java
  src/main/java/io/milvus/client/exception/UnsupportedServerVersion.java
  src/main/proto/common.proto
  src/main/proto/milvus.proto
  src/main/proto/schema.proto
  src/main/proto/status.proto
  src/test/java/io/milvus/client/MilvusGrpcClientTest.java
Labels: enhancement, lgtm, size/XXL, approved, ci-passed

#191 framework && simple connection
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/R.java
  src/main/proto/milvus.proto
Labels: size/L, lgtm, approved, ci-passed

#194 extend client side status enum
  src/main/java/io/milvus/param/R.java
Labels: lgtm, approved, ci-passed, size/M
