Repository milvus-io/milvus-sdk-java, pull requests merged in 2021-09, with the labels that each got.

#199 complete DDL rpc implementation
  examples/main/src/io/milvus/DDLExample.java
  examples/pom.xml
  pom.xml
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/R.java
  src/main/java/io/milvus/param/RpcStatus.java
  src/main/java/io/milvus/param/collection/CreateCollectionParam.java
  src/main/java/io/milvus/param/collection/DescribeCollectionParam.java
  src/main/java/io/milvus/param/collection/DropCollectionParam.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/collection/GetCollectionStatisticsParam.java
  src/main/java/io/milvus/param/collection/HasCollectionParam.java
  src/main/java/io/milvus/param/collection/LoadCollectionParam.java
  src/main/java/io/milvus/param/collection/ReleaseCollectionParam.java
  src/main/java/io/milvus/param/collection/ShowCollectionParam.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
  src/main/java/io/milvus/param/index/DescribeIndexParam.java
  src/main/java/io/milvus/param/index/DropIndexParam.java
  src/main/java/io/milvus/param/index/GetIndexBuildProgressParam.java
  src/main/java/io/milvus/param/index/GetIndexStateParam.java
  src/main/java/io/milvus/param/partition/CreatePartitionParam.java
  src/main/java/io/milvus/param/partition/DropPartitionParam.java
  src/main/java/io/milvus/param/partition/GetPartitionStatisticsParam.java
  src/main/java/io/milvus/param/partition/HasPartitionParam.java
  src/main/java/io/milvus/param/partition/LoadPartitionsParam.java
  src/main/java/io/milvus/param/partition/ReleasePartitionsParam.java
  src/main/java/io/milvus/param/partition/ShowPartitionParam.java
Labels: lgtm, size/XXL, approved, ci-passed

#200 Support basic DDL Operations
  examples/main/io/milvus/DDLExample.java
  examples/main/io/milvus/DMLExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/exception/ParamException.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/MetricType.java
  src/main/java/io/milvus/param/R.java
  src/main/java/io/milvus/param/dml/CalcDistanceParam.java
  src/main/java/io/milvus/param/dml/DeleteParam.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/test/java/io/milvus/client/MilvusClientTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#196 Add development.md for contributor to setup environment(#195)
  DEVELOPMENT.md
Labels: lgtm, approved, ci-passed, size/M

#207 Add control logic param definition
  src/main/java/io/milvus/param/Control/GetMetricsRequestParam.java
  src/main/java/io/milvus/param/Control/GetPersistentSegmentInfoParam.java
  src/main/java/io/milvus/param/Control/GetQuerySegmentInfoParam.java
Labels: size/L, lgtm, approved, ci-passed

#211 pretty code style for newest branch
  examples/main/io/milvus/DDLExample.java
  examples/main/io/milvus/DMLExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/exception/ParamException.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/MetricType.java
  src/main/java/io/milvus/param/R.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/dml/CalcDistanceParam.java
  src/main/java/io/milvus/param/dml/DeleteParam.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
Labels: lgtm, approved, ci-passed, size/XL
