Repository milvus-io/milvus-sdk-java, pull requests merged in 2022-05, with the labels that each got.

#285 Rename import() to bulkload()
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/param/dml/BulkloadParam.java
  src/main/java/io/milvus/param/dml/GetBulkloadStateParam.java
  src/main/java/io/milvus/param/dml/ListBulkloadTasksParam.java
  src/main/java/io/milvus/param/dml/ListImportTasksParam.java
  src/main/java/io/milvus/response/GetBulkloadStateWrapper.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#286 Set index name
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
Labels: lgtm, approved, ci-passed, size/S

#288 Update loadCollection() api
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/collection/LoadCollectionParam.java
  src/main/java/io/milvus/param/partition/LoadPartitionsParam.java
Labels: lgtm, approved, ci-passed, size/M

#289 Implement getReplicas() interface
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/param/control/GetReplicasParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  src/test/java/io/milvus/server/MockMilvusServerImpl.java
Labels: size/L, lgtm, approved, ci-passed

#291 Implement credential interfaces
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/MultiConnectParam.java
  src/main/java/io/milvus/param/credential/CreateCredentialParam.java
  src/main/java/io/milvus/param/credential/DeleteCredentialParam.java
  src/main/java/io/milvus/param/credential/ListCredUsersParam.java
  src/main/java/io/milvus/param/credential/UpdateCredentialParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  src/test/java/io/milvus/server/MockMilvusServerImpl.java
Labels: lgtm, approved, ci-passed, size/XL

#294 Support string field
  docker-compose.yml
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed
