Repository milvus-io/milvus-sdk-java, pull requests merged in 2022-07, with the labels that each got.

#316 Disable String type, only allow VarChar type
  docker-compose.yml
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/S

#317 Add missed index types
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/IndexType.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
Labels: lgtm, approved, ci-passed, size/S

#319 Query failed when collection is empty or improper expression
  docker-compose.yml
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#325 xun.huang@zilliz.com 1.milvus client impl https 2.delete account password log 3.query and search add consistency level.
  .gitignore
  examples/main/io/milvus/GeneralExample.java
  examples/pom.xml
  pom.xml
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/common/clientenum/ConsistencyLevelEnum.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/MultiConnectParam.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/credential/CreateCredentialParam.java
  src/main/java/io/milvus/param/credential/UpdateCredentialParam.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#326 Refine index name
  docker-compose.yml
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/collection/FlushParam.java
  src/main/java/io/milvus/param/collection/LoadCollectionParam.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
  src/main/java/io/milvus/param/index/DescribeIndexParam.java
  src/main/java/io/milvus/param/index/DropIndexParam.java
  src/main/java/io/milvus/param/index/GetIndexBuildProgressParam.java
  src/main/java/io/milvus/param/index/GetIndexStateParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/XL

#327 Add maintainer member
  OWNERS
Labels: lgtm, approved, ci-passed, size/XS

#328 Fix drop index bug
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#329 Fix example
  examples/main/io/milvus/GeneralExample.java
Labels: size/L, lgtm, approved, ci-passed

#330 Fix metric type bug of search param
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#342 Add test case for all supported indexed
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#348 add testcases for partition and so on .
  tests/milvustest/.gitignore
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/BaseTest.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/alias/AlterAliasTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/alias/CreateAliasTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/alias/DropAliasTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/CreateCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/DescribeCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/DropCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/GetCollectionStatisticsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/ReleaseCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/compaction/GetCompactionStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/compaction/ManualCompactionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/credential/DeleteCredentialTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/credential/UpdateCredentialTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/flush/FlushTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/DescribeIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/GetIndexBuildProgressTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/GetIndexStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/other/GetMetricsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/CreatePartitionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/DropPartitionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/LoadPartitionsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/ReleasePartitionsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/segment/GetPersistentSegmentInfoTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/segment/GetQuerySegmentInfoTest.java
  tests/milvustest/src/test/java/resources/milvus-java-sdk-TestCase.xlsx
  tests/milvustest/src/test/java/resources/milvus-java-skd-TestCase.xlsx
Labels: lgtm, size/XXL, approved, ci-passed

#349 Reduce info log
  docker-compose.yml
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
Labels: size/L, lgtm, approved, ci-passed

#351 No need to specify data type for InsertParam
  examples/main/io/milvus/GeneralExample.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/QueryNodeSingleSearch.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/response/DescCollResponseWrapper.java
  src/main/java/io/milvus/response/DescIndexResponseWrapper.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/GetBulkloadStateWrapper.java
  src/main/java/io/milvus/response/MutationResultWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/main/java/io/milvus/response/ShowCollResponseWrapper.java
  src/main/java/io/milvus/response/ShowPartResponseWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  src/test/java/io/milvus/server/MockMilvusServer.java
  src/test/java/io/milvus/server/MockMilvusServerImpl.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
Labels: lgtm, approved, ci-passed, size/XL

#355 modify testcase for 2.1.0-beta4
  tests/milvustest/allure-results/environment.properties
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/DropIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/GetIndexBuildProgressTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/GetIndexStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/CreatePartitionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/LoadPartitionsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/ReleasePartitionsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
  tests/milvustest/src/test/java/resources/run.properties
  tests/milvustest/testngAll.xml
Labels: size/L, lgtm, approved, ci-passed

#362 tag smoke testcase
  tests/milvustest/allure-results/environment.properties
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/BaseTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/alias/AlterAliasTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/alias/CreateAliasTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/alias/DropAliasTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/CreateCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/DescribeCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/DropCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/GetCollectionStatisticsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/HasCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/LoadCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/ReleaseCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/ShowCollectionsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/compaction/GetCompactionStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/compaction/GetCompactionStateWithPlansTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/compaction/ManualCompactionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/connection/CloseTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/connection/ConnectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/credential/CreateCredentialTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/credential/DeleteCredentialTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/credential/ListCredUsersTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/credential/UpdateCredentialTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/flush/FlushTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/flush/GetFlushStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/DescribeIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/DropIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/GetIndexBuildProgressTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/GetIndexStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/DeleteTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/other/GetMetricsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/other/GetReplicasTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/other/LoadBalanceTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/CreatePartitionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/DropPartitionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/GetPartitionStatisticsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/HasPartitionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/LoadPartitionsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/ReleasePartitionsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/ShowPartitionsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/segment/GetPersistentSegmentInfoTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/segment/GetQuerySegmentInfoTest.java
  tests/milvustest/testng.xml
Labels: size/L, lgtm, approved, ci-passed
