Repository milvus-io/milvus-sdk-java, pull requests merged in 2022-10, with the labels that each got.

#384 Fill nq field in search request
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/SearchParam.java
Labels: lgtm, approved, ci-passed, size/XS

#388 Rename bulkload to bulkinsert
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/param/bulkinsert/BulkInsertParam.java
  src/main/java/io/milvus/param/bulkinsert/ListBulkInsertTasksParam.java
  src/main/java/io/milvus/param/collection/GetCollectionStatisticsParam.java
  src/main/java/io/milvus/param/collection/LoadCollectionParam.java
  src/main/java/io/milvus/param/dml/BulkloadParam.java
  src/main/java/io/milvus/param/dml/CalcDistanceParam.java
  src/main/java/io/milvus/param/dml/GetBulkloadStateParam.java
  src/main/java/io/milvus/param/dml/ListBulkloadTasksParam.java
  src/main/java/io/milvus/param/partition/GetPartitionStatisticsParam.java
  src/main/java/io/milvus/response/GetBulkInsertStateWrapper.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/XL

#391 covert connect param host delete start http:// or https://.
  src/main/java/io/milvus/common/constant/MilvusClientConstant.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/MultiConnectParam.java
Labels: approved, ci-passed, size/M

#393 Remove is_row_based flag of bulk_insert()
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/param/bulkinsert/BulkInsertParam.java
  src/main/java/io/milvus/param/bulkinsert/GetBulkInsertStateParam.java
  src/main/java/io/milvus/param/bulkinsert/ListBulkInsertTasksParam.java
Labels: lgtm, approved, ci-passed, size/M
