Repository milvus-io/milvus-sdk-java, pull requests merged in 2022-11, with the labels that each got.

#398 add and modify testcases
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/BaseTest.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/service/CustomerListener.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/FileUtils.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/HttpClientUtils.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/businessflow/Performance.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/businessflow/PerformanceTest2.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/LoadCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/ReleaseCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/ShowCollectionsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/credential/UpdateCredentialTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/DescribeIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/GetIndexBuildProgressTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/limit/BackPressure.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/limit/DDLTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/limit/DMLTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/limit/DQLTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/limit/LimitTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/limit/LimitWriting.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/BulkInsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/BulkLoadTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/GetBulkloadStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/ListBulkInsertTasksTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/ListBulkloadTasksTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/bulkloadStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/AddUserToRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/CreateRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/DropRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/GrantRolePrivilegeTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/RemoveUserFromRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/RevokeRolePrivilegeTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/SelectGrantForRoleAndObject.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/SelectGrantForRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/SelectRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/SelectUserTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/vdc/DBAdminRBACTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/vdc/VectorSearch.java
  tests/milvustest/src/test/java/resources/run.properties
  tests/milvustest/src/test/java/resources/testcase/milvus-java-sdk-TestCase.xlsx
  tests/milvustest/src/test/java/resources/testdata/db_admin.json
  tests/milvustest/src/test/java/resources/testdata/privilege.json
  tests/milvustest/testng.xml
Labels: size/XXL, approved, ci-passed

#400 Update the index interface to be consistent with pymilvus
  docker-compose.yml
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/DescribeIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/DropIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/GetIndexStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/IndexLoadTest.java
Labels: size/L, lgtm, approved, ci-passed

#403 modify testcases and pom.xml
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/service/CustomerListener.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/compaction/GetCompactionStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/compaction/GetCompactionStateWithPlansTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/compaction/ManualCompactionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/BulkLoadStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/ListBulkInsertTasksTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/other/LoadBalanceTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/DropPartitionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/GetPartitionStatisticsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/LoadPartitionsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/AddUserToRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/CreateRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/DropRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/GrantRolePrivilegeTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/SelectGrantForRoleAndObject.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/SelectGrantForRoleTest.java
  tests/milvustest/src/test/java/resources/run.properties
  tests/milvustest/src/test/java/resources/testdata/privilege.json
Labels: size/L

#404 modify java sdk testcases
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/DropIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/IndexLoadTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/AddUserToRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/CreateRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/DropRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/GrantRolePrivilegeTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/RemoveUserFromRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/RevokeRolePrivilegeTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/SelectGrantForRoleAndObject.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/SelectGrantForRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/SelectRoleTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/rbac/SelectUserTest.java
Labels: lgtm, approved, ci-passed, size/M

#405 java sdk ci test
  .github/workflows/java_sdk_ci_test.yaml
  tests/milvustest/src/test/java/resources/docker-compose.yml
  tests/milvustest/src/test/java/resources/run.properties
Labels: size/L, lgtm, approved, ci-passed

#406 Add RBAC example
  examples/main/java/io/milvus/GeneralExample.java
  examples/main/java/io/milvus/RBACExample.java
  examples/pom.xml
Labels: size/L, lgtm, approved, ci-passed

#407 modify testcases and run config
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/service/CustomerListener.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/ListBulkInsertTasksTest.java
  tests/milvustest/src/test/java/resources/run.properties
Labels: size/M

#408 Bump commons-text from 1.6 to 1.10.0
  pom.xml
Labels: approved, size/XS

#410 Enable query pagination
  docker-compose.yml
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed
