Repository milvus-io/milvus-sdk-java, pull requests merged in 2022-08, with the labels that each got.

#365 modify log4j to log4j2 and add testcase
  tests/milvustest/allure-results/environment.properties
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/BaseTest.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/service/CustomerListener.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/service/LogRecord.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/FileUtils.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/PropertyFilesUtil.java
  tests/milvustest/src/main/resources/application.properties
  tests/milvustest/src/main/resources/log4j.properties
  tests/milvustest/src/main/resources/log4j2.xml
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/CreateCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/DropCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/LoadCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/ReleaseCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/ReleasePartitionsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
  tests/milvustest/src/test/java/resources/milvus-java-sdk-TestCase.xlsx
  tests/milvustest/testng.xml
  tests/milvustest/testngAll.xml
Labels: lgtm, size/XXL, approved, ci-passed

#367 Fix keepAliveTimeout timeunit error
  src/main/java/io/milvus/param/ConnectParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/S

#370 Change a log
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
Labels: lgtm, approved, ci-passed, size/XS

#372 Refine consistency level logic
  .github/mergify.yml
  .github/workflows/maven.yml
  src/main/java/io/milvus/connection/QueryNodeListener.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#373 Remove unused constant value
  .github/workflows/maven.yml
  examples/main/io/milvus/GeneralExample.java
  src/main/java/io/milvus/param/Constant.java
Labels: lgtm, approved, ci-passed, size/S

#374 Prepare to release 2.1
  CHANGELOG.md
  README.md
  examples/main/io/milvus/GeneralExample.java
  examples/pom.xml
  pom.xml
  tests/milvustest/pom.xml
Labels: lgtm, approved, ci-passed, size/S

#376 Update changelog.md
  CHANGELOG.md
Labels: lgtm, approved, ci-passed, size/XS
