Repository milvus-io/milvus-sdk-java, pull requests merged in 2023-01, with the labels that each got.

#420 modify failed testcases
  tests/milvustest/src/main/java/com/zilliz/milvustest/entity/FieldType.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/FileUtils.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/K8SUtils.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/MathUtil.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/K8STEST.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/GetCollectionStatisticsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
  tests/milvustest/src/test/java/resources/config/k8s.config
  tests/milvustest/src/test/java/resources/run.properties
Labels: size/L

#422 modify pom.xml2
  tests/milvustest/pom.xml
Labels: size/XS

#423 Prepare to release 2.2.2
  CHANGELOG.md
Labels: lgtm, approved, ci-passed, size/M

#424 Fix unitest failure
  src/main/java/io/milvus/param/ParamUtils.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#425 Fix unitest failure
  src/main/java/io/milvus/param/ParamUtils.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#427 get bulkinsert progress percent value
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/response/GetBulkInsertStateWrapper.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#428 [cherry-pick] Get bulkinsert progress percent value
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/response/GetBulkInsertStateWrapper.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed
