Repository milvus-io/milvus-sdk-java, pull requests merged in 2023-05, with the labels that each got.

#478 modify bulkLoadState testcase
  tests/milvustest/src/main/java/com/zilliz/milvustest/service/CustomerListener.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/businessflow/ConcurrentTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/BulkLoadStateTest.java
Labels: size/L, lgtm, approved, ci-passed

#485 createColl && descColl support dynamicField
  .gitignore
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/collection/CreateCollectionParam.java
  src/main/java/io/milvus/param/collection/FieldType.java
Labels: approved, size/M

#482 add concurrent testcase
  tests/milvustest/README.md
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/businessflow/ConcurrentTest.java
  tests/milvustest/src/test/java/resources/config/k8s.config
  tests/milvustest/testngAll.xml
  tests/milvustest/testngConcurrent.xml
Labels: size/L, lgtm, approved, ci-passed

#488 Fix busy waiting when checking heartbeat
  src/main/java/io/milvus/connection/ServerMonitor.java
Labels: lgtm, approved, ci-passed, size/S

#493 [cherry-pick] Fix busy waiting when checking heartbeat (#488)
  src/main/java/io/milvus/connection/ServerMonitor.java
Labels: lgtm, approved, ci-passed, size/S

#495 upgrade the version of protobuf&proto to fix their CVE
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#496 [cherry-pick] upgrade the version of protobuf&proto to fix their CVE (#495)
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#503 Fix a bug for partition key
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/response/DescCollResponseWrapper.java
Labels: lgtm, approved, ci-passed, size/M

#504 Fix a typo for partition key
  src/main/java/io/milvus/param/ParamUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#508 Optional deadline for remote call
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/ConnectParam.java
Labels: lgtm, approved, ci-passed, size/M

#509 [cherry-pick] Add ignore_growing flag for search/query (#465)
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#511 Partition key collection not allow specify partition name
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/InsertParam.java
Labels: lgtm, approved, ci-passed, size/XS
