Repository milvus-io/milvus-sdk-java, pull requests merged in 2023-06, with the labels that each got.

#522 Fix a bug of partition key
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#523 Show output fields for SearchREsult/QueryResult
  docker-compose.yml
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/QueryResultsWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#526 fix insertRow err and modify example
  examples/main/java/io/milvus/GeneralExample.java
  src/main/java/io/milvus/param/ParamUtils.java
Labels: size/L, ci-passed

#527 Prepare for 2.2.6
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
  src/main/java/io/milvus/response/QueryResultsWrapper.java
Labels: lgtm, approved, ci-passed, size/S

#528 Simple example
  examples/main/java/io/milvus/SimpleExample.java
Labels: size/L, lgtm, approved, ci-passed

#529 add testcases for dynamic json and partition key
  tests/milvustest/allure-results/environment.properties
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/BulkLoadStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/PartitionKeyTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
  tests/milvustest/src/test/java/resources/run.properties
Labels: lgtm, size/XXL, approved, ci-passed

#533 add dynamic and partition key testcases
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/K8SUtils.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/K8STEST.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/load/BulkLoadStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/partition/PartitionKeyTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#535 add high-level support & updatePwd oldPwd can be empty
  examples/main/java/io/milvus/HighLevelExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/common/utils/VectorUtils.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/credential/UpdateCredentialParam.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/highlevel/collection/CreateSimpleCollectionParam.java
  src/main/java/io/milvus/param/highlevel/collection/ListCollectionsParam.java
  src/main/java/io/milvus/param/highlevel/collection/response/ListCollectionsResponse.java
  src/main/java/io/milvus/param/highlevel/dml/DeleteIdsParam.java
  src/main/java/io/milvus/param/highlevel/dml/GetIdsParam.java
  src/main/java/io/milvus/param/highlevel/dml/InsertRowsParam.java
  src/main/java/io/milvus/param/highlevel/dml/QuerySimpleParam.java
  src/main/java/io/milvus/param/highlevel/dml/SearchSimpleParam.java
  src/main/java/io/milvus/param/highlevel/dml/response/DeleteResponse.java
  src/main/java/io/milvus/param/highlevel/dml/response/GetResponse.java
  src/main/java/io/milvus/param/highlevel/dml/response/InsertResponse.java
  src/main/java/io/milvus/param/highlevel/dml/response/QueryResponse.java
  src/main/java/io/milvus/param/highlevel/dml/response/SearchResponse.java
  src/main/java/io/milvus/response/DescCollResponseWrapper.java
  src/main/java/io/milvus/response/MutationResultWrapper.java
  src/main/java/io/milvus/response/QueryResultsWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/main/java/io/milvus/response/ShowCollResponseWrapper.java
  src/main/java/io/milvus/response/basic/RowRecordWrapper.java
Labels: size/XXL, approved

#532 Fix unclosed okhttp response in default heartbeat listener
  src/main/java/io/milvus/connection/ClusterListener.java
Labels: lgtm, approved, ci-passed, size/XS

#536 Prepare for 2.2.7
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/S

#538 Add highlevel testcases
  tests/milvustest/pom.xml
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/serverless/HighLevel.java
Labels: size/L, lgtm, approved, ci-passed

#540 fix highLevel-API error (#539)
  examples/main/java/io/milvus/HighLevelExample.java
  src/main/java/io/milvus/param/highlevel/dml/QuerySimpleParam.java
  src/main/java/io/milvus/param/highlevel/dml/SearchSimpleParam.java
Labels: lgtm, approved, size/M

#541 fix highLevel Example
  examples/main/java/io/milvus/HighLevelExample.java
Labels: lgtm, approved, size/XS

#542 Verify index parameter
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/IndexType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#543 Set log level in runtime
  examples/main/java/io/milvus/HighLevelExample.java
  examples/main/java/io/milvus/SimpleExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/LogLevel.java
Labels: lgtm, approved, ci-passed, size/M

#545 query/search/get/createColl highLevel interface add params consistenc…
  examples/main/java/io/milvus/HighLevelExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/highlevel/collection/CreateSimpleCollectionParam.java
  src/main/java/io/milvus/param/highlevel/dml/GetIdsParam.java
  src/main/java/io/milvus/param/highlevel/dml/QuerySimpleParam.java
  src/main/java/io/milvus/param/highlevel/dml/SearchSimpleParam.java
Labels: lgtm, approved, size/M

#546 add params primaryFieldType and maxLength
  src/main/java/io/milvus/param/highlevel/collection/CreateSimpleCollectionParam.java
Labels: size/M

#548 Prepare for 2.2.8
  CHANGELOG.md
  README.md
  docker-compose.yml
  examples/pom.xml
  pom.xml
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#551 Change default shard number
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/bulkinsert/ListBulkInsertTasksParam.java
  src/main/java/io/milvus/param/collection/CreateCollectionParam.java
  src/main/java/io/milvus/param/highlevel/collection/CreateSimpleCollectionParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/S

#552 Wait milvus server before test start
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#555 Prepare for 2.2.9
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S
