Repository milvus-io/milvus-sdk-java, pull requests merged in 2023-12, with the labels that each got.

#709 Fix a bug of retry
  examples/main/java/io/milvus/GeneralExample.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
Labels: lgtm, approved, ci-passed, size/S

#710 Fix a bug of retry
  examples/main/java/io/milvus/GeneralExample.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
Labels: lgtm, approved, ci-passed, size/S

#711 update code for java sdk support china serverless milvus connect.
  src/main/java/io/milvus/common/constant/MilvusClientConstant.java
Labels: lgtm, approved, ci-passed, size/XS

#712 update code for java sdk support china serverless milvus connect.
  src/main/java/io/milvus/common/constant/MilvusClientConstant.java
Labels: lgtm, approved, ci-passed, size/XS

#713 Upgrade grpc from 1.46 to 1.59.1
  docker-compose.yml
  pom.xml
Labels: lgtm, approved, ci-passed

#714 Upgrade grpc from 1.46 to 1.59.1
  docker-compose.yml
  pom.xml
Labels: lgtm, approved, ci-passed

#716 Add withPartitionName for DeleteIdsParam
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/highlevel/dml/DeleteIdsParam.java
Labels: lgtm, approved, ci-passed

#715 Add withPartitionName for DeleteIdsParam
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/highlevel/dml/DeleteIdsParam.java
Labels: lgtm, approved, ci-passed, size/S

#717 Upgrade grpc from 1.46 to 1.59.1
  docker-compose.yml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#718 Add withPartitionName for DeleteIdsParam
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/highlevel/dml/DeleteIdsParam.java
Labels: lgtm, approved, ci-passed, size/S

#723 Remove unsupported index types
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/IndexLoadTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
Labels: size/L, lgtm, approved, ci-passed

#724 chore: logInfo is too high for recording request params
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
Labels: size/L, lgtm, approved, ci-passed

#727 [cherry-pick] chore: logInfo is too high for recording request params (#724)
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
Labels: size/L, approved, ci-passed
