Repository milvus-io/milvus-sdk-java, pull requests merged in 2023-04, with the labels that each got.

#465 Add ignore_growing flag for search/query
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#467 Prepare for 2.2.5
  CHANGELOG.md
  README.md
  docker-compose.yml
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#470 modify testcase for getCollectionStatistics
  tests/milvustest/pom.xml
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/GetCollectionStatisticsTest.java
  tests/milvustest/src/test/java/resources/temp/rowJson0.json
Labels: lgtm, size/XXL, approved, ci-passed

#473 add interface: flushAll/getFlushAllState
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/param/control/GetFlushAllStateParam.java
  src/main/java/io/milvus/param/control/GetFlushStateParam.java
Labels: size/L

#475 add database interface
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/param/collection/CreateDatabaseParam.java
  src/main/java/io/milvus/param/collection/DropDatabaseParam.java
Labels: size/L

#476 finish database interface support
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
Labels: approved, size/S
