Repository milvus-io/milvus-sdk-java, pull requests merged in 2023-03, with the labels that each got.

#448 add modify dependency version function2
  tests/milvustest/pom.xml
  tests/milvustest/pom.xslt
  tests/milvustest/src/test/java/com/zilliz/milvustest/ModifyXml.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/IndexLoadTest.java
Labels: size/L, lgtm, approved, ci-passed

#450 add support rename
  pom.xml
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/param/collection/RenameCollectionParam.java
Labels: size/L, approved

#451 add protobuf-java to fix java sdk 2.2.3 running failed
  tests/milvustest/pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#453 add protobuf-java to fix java sdk 2.2.3 running failed (#451)
  tests/milvustest/pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#456 Use the same grpc version as milvus-proto repo
  examples/pom.xml
  pom.xml
  tests/milvustest/pom.xml
Labels: lgtm, approved, ci-passed, size/S

#457 Use the same grpc version as milvus-proto repo
  examples/pom.xml
  pom.xml
  tests/milvustest/pom.xml
Labels: lgtm, approved, ci-passed, size/S

#460 Add alterCollection interface
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/collection/AlterCollectionParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  src/test/java/io/milvus/server/MockMilvusServerImpl.java
Labels: size/L, lgtm, approved, ci-passed

#461 [cherry-pick] Add alterCollection interface
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/collection/AlterCollectionParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  src/test/java/io/milvus/server/MockMilvusServerImpl.java
Labels: size/L, lgtm, approved, ci-passed

#463 Update docker image
  docker-compose.yml
Labels: lgtm, approved, ci-passed, size/XS
