Repository milvus-io/milvus-sdk-java, pull requests merged in 2023-08, with the labels that each got.

#568 Support retry
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
Labels: lgtm, approved, ci-passed, size/XL

#569 Refine error handling
  examples/main/java/io/milvus/TLSExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
Labels: size/L, lgtm, approved, ci-passed

#571 add tls testcase
  tests/milvustest/src/test/java/com/zilliz/milvustest/tls/TLSTest.java
  tests/milvustest/src/test/java/resources/tls/ca.key
  tests/milvustest/src/test/java/resources/tls/ca.pem
  tests/milvustest/src/test/java/resources/tls/ca.srl
  tests/milvustest/src/test/java/resources/tls/client.csr
  tests/milvustest/src/test/java/resources/tls/client.key
  tests/milvustest/src/test/java/resources/tls/client.pem
  tests/milvustest/src/test/java/resources/tls/gen.sh
  tests/milvustest/src/test/java/resources/tls/openssl.cnf
  tests/milvustest/src/test/java/resources/tls/server.csr
  tests/milvustest/src/test/java/resources/tls/server.key
  tests/milvustest/src/test/java/resources/tls/server.pem
Labels: lgtm, approved, ci-passed, size/XL

#572 Varchar index name compatible with 2.2.12
  docker-compose.yml
  src/main/java/io/milvus/param/index/CreateIndexParam.java
Labels: lgtm, approved, ci-passed, size/S

#573 Using milvus 2.2.12 for test
  docker-compose.yml
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#574 Prepare for release v2.2.11
  CHANGELOG.md
  README.md
  examples/main/java/io/milvus/GeneralExample.java
  examples/main/java/io/milvus/HighLevelExample.java
  examples/main/java/io/milvus/SimpleExample.java
  examples/pom.xml
  pom.xml
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
Labels: lgtm, approved, ci-passed, size/M

#576 Fix bug of scalar field index
  docker-compose.yml
  examples/main/java/io/milvus/GeneralExample.java
  src/main/java/io/milvus/param/IndexType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#577 Prepare for 2.2.12
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#580 Implement Upsert interface
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/param/IndexType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/UpsertParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  tests/milvustest/pom.xml
Labels: lgtm, approved, ci-passed, size/XL

#582 Support pass bulk insert options
  src/main/java/io/milvus/param/bulkinsert/BulkInsertParam.java
Labels: lgtm, approved, ci-passed, size/S

#583 Prepare for 2.3.0
  CHANGELOG.md
  README.md
Labels: lgtm, approved, ci-passed, size/S

#584 Fix bug of highLevel-delete
  src/main/java/io/milvus/common/utils/VectorUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#585 Fix bug of highLevel-delete
  src/main/java/io/milvus/common/utils/VectorUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#586 Enable keepalive by default
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/S

#587 [cherry-pick] Enable keepalive by default
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/S

#589 Fix bug of highLevel-get
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
Labels: lgtm, approved, ci-passed, size/XS

#590 Fix bug of highLevel-get
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
Labels: lgtm, approved, ci-passed, size/XS

#592 modify testcases and verify highlevel bug
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/service/CustomerListener.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/IndexLoadTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/DeleteTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/UpsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/serverless/HighLevel.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/serverless/HighLevelTest.java
  tests/milvustest/src/test/java/resources/run.properties
  tests/milvustest/testng.xml
Labels: lgtm, approved, ci-passed, size/XL

#593 modify testcases and verify highlevel bug (#592)
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/service/CustomerListener.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/IndexLoadTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/DeleteTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/UpsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchAsyncTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/serverless/HighLevel.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/serverless/HighLevelTest.java
  tests/milvustest/src/test/java/resources/run.properties
  tests/milvustest/testng.xml
Labels: lgtm, approved, ci-passed, size/XL

#597 Remove deprecated methods
  examples/main/java/io/milvus/GeneralExample.java
  src/main/java/io/milvus/connection/QueryNodeListener.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/highlevel/dml/QuerySimpleParam.java
  src/main/java/io/milvus/param/highlevel/dml/SearchSimpleParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#598 Remove deprecated methods
  examples/main/java/io/milvus/GeneralExample.java
  src/main/java/io/milvus/connection/QueryNodeListener.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/highlevel/dml/QuerySimpleParam.java
  src/main/java/io/milvus/param/highlevel/dml/SearchSimpleParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#604 Add test for highLevel-get and highLevel-delete
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/tls/TLSTest.java
Labels: size/L, lgtm, approved, ci-passed

#605 Add test for highLevel-get and highLevel-delete
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#606 [cherry-pick] Fix bug of highLevel-get and highLevel-delete and Add test
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/common/utils/VectorUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/tls/TLSTest.java
Labels: size/L, lgtm, approved, ci-passed

#610 Fix a bug for binary vector
  README.md
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#608 Fix a bug for binary vector
  README.md
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#609 Fix a bug of binary vectors
  README.md
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M
