Repository milvus-io/milvus-sdk-java, pull requests merged in 2023-02, with the labels that each got.

#437 Upgrade kotlin version
  .github/workflows/java_sdk_ci_test.yaml
  .github/workflows/maven.yml
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#438 Upgrade kotlin version
  .github/workflows/java_sdk_ci_test.yaml
  .github/workflows/maven.yml
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#441 modify testcase for index
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/GetCollectionStatisticsTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/DropIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/IndexLoadTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/other/GetReplicasTest.java
Labels: approved, ci-passed, size/S

#442 Fix example error
  examples/main/java/io/milvus/GeneralExample.java
Labels: lgtm, approved, ci-passed, size/S

#443 Fix example error
  examples/main/io/milvus/GeneralExample.java
Labels: lgtm, approved, ci-passed, size/S

#444 Prepare for v2.2.3
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S
