Repository milvus-io/milvus-sdk-java, pull requests merged in 2023-10, with the labels that each got.

#656 Fix a bug of highlevel interface
  examples/main/java/io/milvus/HighLevelExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/highlevel/dml/response/SearchResponse.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
Labels: lgtm, approved, ci-passed, size/M

#657 Fix a bug of highlevel interface
  examples/main/java/io/milvus/HighLevelExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/highlevel/dml/response/SearchResponse.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
Labels: lgtm, approved, ci-passed, size/M

#658 Fix a bug of highlevel interface
  examples/main/java/io/milvus/HighLevelExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/highlevel/dml/response/SearchResponse.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
Labels: lgtm, approved, ci-passed, size/M

#659 fix connectparam and hascollection param databaseName can be null.
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/MultiConnectParam.java
  src/main/java/io/milvus/param/collection/HasCollectionParam.java
Labels: lgtm, approved, ci-passed, size/XS

#660 add testcases for rangeSearch、renameCollection and so on
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/BaseTest.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/MathUtil.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/DropCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/RenameCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/database/DatabaseTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/flush/FlushTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/DeleteTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/RangeSearchTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#661 fix connectparam and hascollection param databaseName can be null.
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/MultiConnectParam.java
  src/main/java/io/milvus/param/collection/HasCollectionParam.java
Labels: lgtm, approved, ci-passed, size/XS

#662 fix connectparam and hascollection param databaseName can be null.
  src/main/java/io/milvus/param/ConnectParam.java
  src/main/java/io/milvus/param/MultiConnectParam.java
  src/main/java/io/milvus/param/collection/HasCollectionParam.java
Labels: lgtm, approved, ci-passed, size/XS

#665 add testcases for rangeSearch、renameCollection and so on (#660)
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/BaseTest.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/MathUtil.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/DropCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/RenameCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/database/DatabaseTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/flush/FlushTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/DeleteTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/RangeSearchTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#666 fix only cloud serverless cluster port must be 443.
  src/main/java/io/milvus/common/constant/MilvusClientConstant.java
  src/main/java/io/milvus/param/ConnectParam.java
Labels: approved, ci-passed, size/S

#667 docs(README): stop calling groovy as grails / add gradle on kotlin usage
  README.md
Labels: lgtm, approved, ci-passed, size/S

#670 [cherry-pick] docs: stop calling groovy as grails (#667)
  README.md
Labels: lgtm, approved, ci-passed, size/S

#669 [cherry-pick] docs: stop calling groovy as grails (#667)
  README.md
Labels: lgtm, approved, ci-passed, size/S

#668 Support Array type field
  docker-compose.yml
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/UpsertParam.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/QueryResultsWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#671 Support Array type field
  docker-compose.yml
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/UpsertParam.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/QueryResultsWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#674 Support insert dynamic values by column-based
  src/main/java/io/milvus/param/ParamUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#675 Support insert dynamic values by column-based
  src/main/java/io/milvus/param/ParamUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#676 Update readme
  CHANGELOG.md
  README.md
Labels: lgtm, approved, ci-passed, size/S

#677 deleteIds Marked as deprecated
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/highlevel/dml/response/DeleteResponse.java
  src/main/java/io/milvus/response/MutationResultWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/serverless/HighLevelTest.java
Labels: lgtm, approved, ci-passed, size/S

#678 deleteIds Marked as deprecated
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/highlevel/dml/response/DeleteResponse.java
  src/main/java/io/milvus/response/MutationResultWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#679 deleteIds Marked as deprecated
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/highlevel/dml/response/DeleteResponse.java
  src/main/java/io/milvus/response/MutationResultWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/serverless/HighLevelTest.java
Labels: lgtm, approved, ci-passed, size/S

#683 fix connection param user databasename not take effect.
  src/main/java/io/milvus/param/ConnectParam.java
Labels: lgtm, approved, ci-passed, size/XS

#684 fix connection param user databasename not take effect.
  src/main/java/io/milvus/param/ConnectParam.java
Labels: approved, size/XS

#686 add testcases with array field (#685)
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/CreateCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/flush/GetFlushStateTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/IndexLoadTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/serverless/HighLevelTest.java
Labels: size/L, lgtm, approved, ci-passed

#688 Update readme
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#690 Support insert dynamic values by column-based
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#691 Prepare for 2.2.15
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S
