Repository milvus-io/milvus-sdk-java, pull requests merged in 2023-09, with the labels that each got.

#615 Add COSINE metric type
  docker-compose.yml
  src/main/java/io/milvus/param/MetricType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#616 [cherry-pick] Add COSINE metric type
  docker-compose.yml
  src/main/java/io/milvus/param/MetricType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#613 fix cve for commons.text
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#617 Prepare for 2.2.13
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#621 Prepare for v2.3.1
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#622 [cherry-pick] fix cve for commons.text (#613)
  pom.xml
Labels: approved, ci-passed, size/XS

#628 Fix the bug that consistency level is ignored in search() interface
  src/main/java/io/milvus/param/ParamUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#629 Fix the bug that consistency level is ignored in search() interface
  src/main/java/io/milvus/param/ParamUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#630 Fix the bug that consistency level is ignored in search() interface
  src/main/java/io/milvus/param/ParamUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#631 fix cve for commons.text
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#634 Set log level for MilvusMultiServiceClient
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#635 Set log level for MilvusMultiServiceClient
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#637 Set log level for MilvusMultiServiceClient
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#639 Pass database name for MilvusMultiServiceClient
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
Labels: lgtm, approved, ci-passed, size/XS

#638 Pass database name for MilvusMultiServiceClient
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
Labels: lgtm, approved, ci-passed, size/XS

#640 Pass database name for MilvusMultiServiceClient
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
Labels: lgtm, approved, ci-passed, size/XS

#641 Prepare for v2.2.14
  CHANGELOG.md
  README.md
  docker-compose.yml
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#642 Prepare for v2.3.2
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#644 [upsert] Fix NPE in case of non empty database name
  src/main/java/io/milvus/param/ParamUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#648 [upsert] Fix NPE in case of non empty database name (#644)
  src/main/java/io/milvus/param/ParamUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#649 Update getFlushState api
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/param/control/GetFlushStateParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#650 Update getFlushState api
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/param/control/GetFlushStateParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#652 Fix some vulnerabilities
  pom.xml
  tests/milvustest/pom.xml
Labels: lgtm, approved, ci-passed, size/S

#653 Fix some vulnerabilities
  pom.xml
  tests/milvustest/pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#651 Fix some vulnerabilities
  pom.xml
  tests/milvustest/pom.xml
Labels: lgtm, approved, ci-passed, size/S
