Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-09, with the labels that each got.

#1058 fix concat expr error
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
Labels: lgtm, approved, ci-passed, size/XS

#1059 fix concat expr error
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
Labels: lgtm, approved, ci-passed, size/XS

#1060 fix concat expr error
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
Labels: lgtm, approved, ci-passed, size/XS

#1063 [cherry-pick] Ensure compatibility of v1 cloud import interface
  src/main/java/io/milvus/bulkwriter/BaseCloudImport.java
  src/main/java/io/milvus/bulkwriter/CloudImport.java
  src/main/java/io/milvus/bulkwriter/CloudImportV2.java
  src/main/java/io/milvus/bulkwriter/response/ListImportJobsResponse.java
  src/main/java/io/milvus/bulkwriter/response/Record.java
  src/main/java/io/milvus/bulkwriter/response/v2/ListImportJobsV2Response.java
Labels: size/L, lgtm, approved, ci-passed

#1064 Override toString() for InsertParam/SearchParam
  .github/workflows/java_sdk_ci_test.yaml
  src/main/java/io/milvus/param/dml/AnnSearchParam.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/dml/UpsertParam.java
  src/main/java/io/milvus/param/highlevel/dml/InsertRowsParam.java
  src/main/java/io/milvus/param/highlevel/dml/SearchSimpleParam.java
Labels: size/L, lgtm, approved, ci-passed

#1065 Override toString() for InsertParam/SearchParam
  .github/workflows/java_sdk_ci_test.yaml
  src/main/java/io/milvus/param/dml/AnnSearchParam.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/dml/UpsertParam.java
  src/main/java/io/milvus/param/highlevel/dml/InsertRowsParam.java
  src/main/java/io/milvus/param/highlevel/dml/SearchSimpleParam.java
Labels: size/L, lgtm, approved, ci-passed

#1066 Override toString() for InsertParam/SearchParam
  .github/workflows/java_sdk_ci_test.yaml
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/dml/UpsertParam.java
  src/main/java/io/milvus/param/highlevel/dml/InsertRowsParam.java
  src/main/java/io/milvus/param/highlevel/dml/SearchSimpleParam.java
Labels: size/L, lgtm, approved, ci-passed

#1067 Adding ability to use javax SSLContext directly when setting up connectConfig.
  src/main/java/io/milvus/v2/client/ConnectConfig.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1068 Adding ability to use javax SSLContext directly when setting up connectConfig.
  src/main/java/io/milvus/v2/client/ConnectConfig.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1070 Prepare for v2.4.4
  CHANGELOG.md
  README.md
  docker-compose.yml
  examples/pom.xml
  pom.xml
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1071 Prepare for v2.3.10
  CHANGELOG.md
  README.md
  examples/main/java/io/milvus/v1/ClientPoolExample.java
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1069 Prepare for v2.4.4
  CHANGELOG.md
  README.md
  docker-compose.yml
  examples/pom.xml
  pom.xml
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1072 add BITMAP index type to IndexType and updated BITMAP related cases
  src/main/java/io/milvus/param/IndexType.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/CreateIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
Labels: lgtm, approved, ci-passed, size/M

#1074 Remove dependency of log4j-slf4j-impl
  pom.xml
  src/main/java/io/milvus/common/utils/VectorUtils.java
  src/main/java/io/milvus/param/highlevel/collection/CreateSimpleCollectionParam.java
  src/main/java/io/milvus/param/highlevel/dml/DeleteIdsParam.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1075 Remove dependency of log4j-slf4j-impl
  pom.xml
  src/main/java/io/milvus/common/utils/VectorUtils.java
  src/main/java/io/milvus/param/highlevel/collection/CreateSimpleCollectionParam.java
  src/main/java/io/milvus/param/highlevel/dml/DeleteIdsParam.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1076 Remove dependency of log4j-slf4j-impl
  pom.xml
  src/main/java/io/milvus/common/utils/VectorUtils.java
  src/main/java/io/milvus/param/highlevel/collection/CreateSimpleCollectionParam.java
  src/main/java/io/milvus/param/highlevel/dml/DeleteIdsParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1079 Refine example
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  examples/main/java/io/milvus/v1/resourcegroup/ResourceGroupManagement.java
  examples/pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1080 Refine example
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  examples/main/java/io/milvus/v1/resourcegroup/ResourceGroupManagement.java
  examples/pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1081 Refine example
  examples/main/java/io/milvus/v1/BulkWriterExample.java
Labels: lgtm, approved, ci-passed, size/XS

#1083 Support nullable and default value
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/QueryResultsWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/main/java/io/milvus/v2/utils/DataUtils.java
  src/main/java/io/milvus/v2/utils/SchemaUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1085 Support clustering key
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1086 Support clustering key
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1088 Refine code
  examples/main/resources/log4j.properties
  examples/pom.xml
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/exception/MilvusClientException.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
Labels: lgtm, approved, ci-passed, size/M

#1089 Refine code
  examples/main/resources/log4j.properties
  examples/pom.xml
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/exception/MilvusClientException.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
Labels: lgtm, approved, ci-passed, size/M

#1090 Refine code
  examples/main/resources/log4j.properties
  examples/pom.xml
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/exception/MilvusClientException.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
Labels: lgtm, approved, ci-passed, size/M

#1092 Support partial load
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/collection/LoadCollectionParam.java
  src/main/java/io/milvus/param/partition/LoadPartitionsParam.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/LoadCollectionReq.java
  src/main/java/io/milvus/v2/service/partition/PartitionService.java
  src/main/java/io/milvus/v2/service/partition/request/LoadPartitionsReq.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1091 Support partial load
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/collection/LoadCollectionParam.java
  src/main/java/io/milvus/param/partition/LoadPartitionsParam.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/LoadCollectionReq.java
  src/main/java/io/milvus/v2/service/partition/PartitionService.java
  src/main/java/io/milvus/v2/service/partition/request/LoadPartitionsReq.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed
