Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-07, with the labels that each got.

#957 DescribeIndex enhancement
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/common/clientenum/ConsistencyLevelEnum.java
  src/main/java/io/milvus/param/IndexBuildState.java
  src/main/java/io/milvus/param/index/DescribeIndexParam.java
  src/main/java/io/milvus/response/DescCollResponseWrapper.java
  src/main/java/io/milvus/response/DescIndexResponseWrapper.java
  src/main/java/io/milvus/v2/common/IndexBuildState.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/index/response/DescribeIndexResp.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#959 DescribeIndex enhancement
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/common/clientenum/ConsistencyLevelEnum.java
  src/main/java/io/milvus/param/IndexBuildState.java
  src/main/java/io/milvus/param/index/DescribeIndexParam.java
  src/main/java/io/milvus/response/DescCollResponseWrapper.java
  src/main/java/io/milvus/response/DescIndexResponseWrapper.java
  src/main/java/io/milvus/v2/common/IndexBuildState.java
  src/main/java/io/milvus/v2/common/IndexParam.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/index/response/DescribeIndexResp.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#958 DescribeIndex enhancement
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/common/clientenum/ConsistencyLevelEnum.java
  src/main/java/io/milvus/param/IndexBuildState.java
  src/main/java/io/milvus/param/index/DescribeIndexParam.java
  src/main/java/io/milvus/response/DescCollResponseWrapper.java
  src/main/java/io/milvus/response/DescIndexResponseWrapper.java
  src/main/java/io/milvus/v2/common/IndexBuildState.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/index/response/DescribeIndexResp.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#955 enhance: changes to propagate traceid from client
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#961 [cherry-pick] changes to propagate tracid from client (#955)
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#963 enhance: Remove the logic to set replica_number=1 by default
  src/main/java/io/milvus/param/collection/LoadCollectionParam.java
  src/main/java/io/milvus/param/partition/LoadPartitionsParam.java
Labels: lgtm, approved, ci-passed, size/S

#960 BulkWriter supports Float16Vector/BFloat16Vector/SparseVector
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/Buffer.java
  src/main/java/io/milvus/bulkwriter/BulkWriter.java
  src/main/java/io/milvus/bulkwriter/common/utils/ParquetUtils.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/QueryResultsWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#965 BulkWriter supports Float16Vector/BFloat16Vector/SparseVector
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/Buffer.java
  src/main/java/io/milvus/bulkwriter/BulkWriter.java
  src/main/java/io/milvus/bulkwriter/common/utils/ParquetUtils.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/QueryResultsWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#969 modify v2 testcase and ci.yaml
  .github/workflows/java_sdk_ci_test.yaml
  tests/milvustest/allure-results/environment.properties
  tests/milvustest/src/test/java/resources/run.properties
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/DescribeCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/DescribeIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/DeleteTest.java
Labels: lgtm, approved, ci-passed, size/S

#970 [cherry-pick]-modify v2 testcase and ci.yaml
  .github/workflows/java_sdk_ci_test.yaml
  tests/milvustest/allure-results/environment.properties
  tests/milvustest/src/test/java/resources/run.properties
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/DescribeCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/DescribeIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/DeleteTest.java
Labels: lgtm, approved, ci-passed, size/S

#971 add BITMAP index cases
  src/main/java/io/milvus/v2/common/IndexParam.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/params/FieldParam.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/CreateIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
Labels: size/L, lgtm, approved, ci-passed

#973 Prepare for v2.4.2
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#968 optim bulkWriter for support enableVirtualStyleEndpoint
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriter.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/CloudStorage.java
  src/main/java/io/milvus/bulkwriter/connect/S3ConnectParam.java
  src/main/java/io/milvus/bulkwriter/storage/client/MinioStorageClient.java
Labels: lgtm, approved, ci-passed, size/M

#975 [cherry-pick] optim bulkWriter for support enableVirtualStyleEndpoint
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriter.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/CloudStorage.java
  src/main/java/io/milvus/bulkwriter/connect/S3ConnectParam.java
  src/main/java/io/milvus/bulkwriter/storage/client/MinioStorageClient.java
Labels: lgtm, approved, ci-passed, size/M

#976 [cherry-pick] optim bulkWriter for support enableVirtualStyleEndpoint
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriter.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/CloudStorage.java
  src/main/java/io/milvus/bulkwriter/connect/S3ConnectParam.java
  src/main/java/io/milvus/bulkwriter/storage/client/MinioStorageClient.java
Labels: lgtm, approved, ci-passed, size/M

#981 Update changelog
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#989 Refine code
  examples/main/java/io/milvus/v1/HybridSearchExample.java
  examples/main/java/io/milvus/v1/SimpleExample.java
  pom.xml
  src/main/java/io/milvus/response/QueryResultsWrapper.java
Labels: lgtm, approved, ci-passed, size/S

#990 Refine code
  examples/main/java/io/milvus/v1/HybridSearchExample.java
  examples/main/java/io/milvus/v1/SimpleExample.java
  pom.xml
  src/main/java/io/milvus/response/QueryResultsWrapper.java
Labels: lgtm, approved, ci-passed, size/S

#991 Fix testcontainers dependency scope
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1000 test: update BITMAP index cases
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/CreateIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
Labels: lgtm, approved, ci-passed, size/S

#995 Fix testcontainers dependency scope (#991)
  pom.xml
  src/main/java/io/milvus/response/DescCollResponseWrapper.java
  src/main/java/io/milvus/response/DescDBResponseWrapper.java
Labels: lgtm, approved, ci-passed, size/S

#999 [cherry-pick] changes to propagate tracid from client (#955)
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/M

#994 Fix testcontainers dependency scope (#991)
  pom.xml
  src/main/java/io/milvus/response/DescCollResponseWrapper.java
  src/main/java/io/milvus/response/DescDBResponseWrapper.java
Labels: lgtm, approved, ci-passed, size/S
