Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-10, with the labels that each got.

#1094 Fix a bug of index extra parameters
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/index/response/DescribeIndexResp.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1095 Fix a bug of index extra parameters
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/index/response/DescribeIndexResp.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1096 Fix a bug of index extra parameters
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/index/response/DescribeIndexResp.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1100 Prepare for v2.4.5
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1105 Fix a pre-connect timeout issue
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
Labels: lgtm, approved, ci-passed, size/XS

#1106 Fix a pre-connect timeout issue
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
Labels: lgtm, approved, ci-passed, size/XS

#1104 Fix a pre-connect timeout issue
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
Labels: lgtm, approved, ci-passed, size/XS

#1098 Adjust the CloudImport method to align with the logic of SDKs in others
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/BaseCloudImport.java
  src/main/java/io/milvus/bulkwriter/CloudImport.java
  src/main/java/io/milvus/bulkwriter/CloudImportV2.java
  src/main/java/io/milvus/bulkwriter/request/BulkImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/GetImportProgressRequest.java
  src/main/java/io/milvus/bulkwriter/request/ListImportJobsRequest.java
  src/main/java/io/milvus/bulkwriter/request/v2/ListImportJobsV2Request.java
  src/main/java/io/milvus/bulkwriter/response/GetImportProgressResponse.java
  src/main/java/io/milvus/bulkwriter/response/ListImportJobsResponse.java
  src/main/java/io/milvus/bulkwriter/response/v2/GetImportProgressV2Response.java
  src/main/java/io/milvus/bulkwriter/response/v2/ListImportJobsV2Response.java
Labels: size/L, lgtm, approved, ci-passed

#1099 [Cherry-Pick] Adjust the CloudImport method to align with the logic of SDKs in othe…
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/BaseCloudImport.java
  src/main/java/io/milvus/bulkwriter/CloudImport.java
  src/main/java/io/milvus/bulkwriter/CloudImportV2.java
  src/main/java/io/milvus/bulkwriter/request/BulkImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/GetImportProgressRequest.java
  src/main/java/io/milvus/bulkwriter/request/ListImportJobsRequest.java
  src/main/java/io/milvus/bulkwriter/request/v2/ListImportJobsV2Request.java
  src/main/java/io/milvus/bulkwriter/response/GetImportProgressResponse.java
  src/main/java/io/milvus/bulkwriter/response/ListImportJobsResponse.java
  src/main/java/io/milvus/bulkwriter/response/v2/GetImportProgressV2Response.java
  src/main/java/io/milvus/bulkwriter/response/v2/ListImportJobsV2Response.java
Labels: size/L, lgtm, approved, ci-passed

#1107 Add collection related cases for null and default value support
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonData.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/CreateCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/DescribeCollectionTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1110 Support Milvus import-related APIs
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/BaseBulkImport.java
  src/main/java/io/milvus/bulkwriter/BulkImport.java
  src/main/java/io/milvus/bulkwriter/request/describe/BaseDescribeImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/describe/CloudDescribeImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/describe/MilvusDescribeImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/import_/BaseImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/import_/CloudImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/list/BaseListImportJobsRequest.java
  src/main/java/io/milvus/bulkwriter/request/list/CloudListImportJobsRequest.java
  src/main/java/io/milvus/bulkwriter/request/list/MilvusListImportJobsRequest.java
Labels: size/L, lgtm, approved, ci-passed

#1111 [cherry-pick] Support Milvus import-related APIs
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/BaseBulkImport.java
  src/main/java/io/milvus/bulkwriter/BulkImport.java
  src/main/java/io/milvus/bulkwriter/request/describe/BaseDescribeImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/describe/CloudDescribeImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/describe/MilvusDescribeImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/import_/BaseImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/import_/CloudImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/list/BaseListImportJobsRequest.java
  src/main/java/io/milvus/bulkwriter/request/list/CloudListImportJobsRequest.java
  src/main/java/io/milvus/bulkwriter/request/list/MilvusListImportJobsRequest.java
Labels: size/L, lgtm, approved, ci-passed

#1108 Add query and search related cases for null and default value support
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/BaseTest.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/InsertTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/QueryTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/UpsertTest.java
Labels: size/L, lgtm, approved, ci-passed

#1109 Remove Jackson dependence
  examples/main/java/io/milvus/v1/HighLevelExample.java
  examples/pom.xml
  pom.xml
  src/main/java/io/milvus/bulkwriter/Buffer.java
  src/main/java/io/milvus/bulkwriter/BulkImport.java
  src/main/java/io/milvus/bulkwriter/BulkWriter.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/common/utils/JacksonUtils.java
  src/main/java/io/milvus/common/utils/JsonUtils.java
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/ranker/WeightedRanker.java
  src/main/java/io/milvus/v2/service/vector/request/ranker/WeightedRanker.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
  src/test/java/io/milvus/v2/service/vector/VectorTest.java
Labels: size/L, lgtm, approved, ci-passed

#1113 Remove Jackson dependence
  examples/main/java/io/milvus/v1/HighLevelExample.java
  examples/pom.xml
  pom.xml
  src/main/java/io/milvus/bulkwriter/Buffer.java
  src/main/java/io/milvus/bulkwriter/BulkImport.java
  src/main/java/io/milvus/bulkwriter/BulkWriter.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/common/utils/JacksonUtils.java
  src/main/java/io/milvus/common/utils/JsonUtils.java
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/ranker/WeightedRanker.java
  src/main/java/io/milvus/v2/service/vector/request/ranker/WeightedRanker.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
  src/test/java/io/milvus/v2/service/vector/VectorTest.java
Labels: size/L, lgtm, approved, ci-passed

#1114 Add enableDynamicField flag in V2 CollectionSchema
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
  src/test/java/io/milvus/v2/service/collection/CollectionTest.java
Labels: lgtm, approved, ci-passed, size/M

#1115 Add enableDynamicField flag in V2 CollectionSchema
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
  src/test/java/io/milvus/v2/service/collection/CollectionTest.java
Labels: lgtm, approved, ci-passed, size/M

#1117 Bulkwriter supports V2 schema
  examples/main/java/io/milvus/v2/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/LocalBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/common/utils/V2AdapterUtils.java
  src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#1119 Bulkwriter supports V2 schema
  examples/main/java/io/milvus/v2/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/LocalBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/common/utils/V2AdapterUtils.java
  src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#1120 milvusImportRestful add partitionName field
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
Labels: lgtm, approved, ci-passed, size/XS

#1121 [cherry-pick] milvusImportRestful add partitionName field #1120
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
Labels: lgtm, approved, ci-passed, size/XS

#1116 Log enhancement: Use slf4j.Logger to replace System.out and print the exception stack trace.
  src/main/java/io/milvus/pool/ClientPool.java
  src/main/java/io/milvus/pool/PoolClientFactory.java
Labels: lgtm, approved, ci-passed, size/S

#1123 Prepare for v2.4.6
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1124 Log enhancement: Use slf4j.Logger to replace System.out and print the…
  src/main/java/io/milvus/pool/ClientPool.java
  src/main/java/io/milvus/pool/PoolClientFactory.java
Labels: lgtm, approved, ci-passed, size/S

#1128 Support setting properties for CreateCollectionRequest
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1129 Support Session consistency level for V1 and V2
  examples/main/java/io/milvus/v1/ConsistencyLevelExample.java
  examples/main/java/io/milvus/v2/ConsistencyLevelExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/common/clientenum/ConsistencyLevelEnum.java
  src/main/java/io/milvus/common/utils/GTsDict.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/QueryIteratorParam.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchIteratorParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/v2/common/ConsistencyLevel.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/request/HybridSearchReq.java
  src/main/java/io/milvus/v2/service/vector/request/QueryIteratorReq.java
  src/main/java/io/milvus/v2/service/vector/request/QueryReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchIteratorReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1130 Support Session consistency level for V1 and V2
  examples/main/java/io/milvus/v1/ConsistencyLevelExample.java
  examples/main/java/io/milvus/v2/ConsistencyLevelExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/common/clientenum/ConsistencyLevelEnum.java
  src/main/java/io/milvus/common/utils/GTsDict.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/QueryIteratorParam.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchIteratorParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/v2/common/ConsistencyLevel.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/request/HybridSearchReq.java
  src/main/java/io/milvus/v2/service/vector/request/QueryIteratorReq.java
  src/main/java/io/milvus/v2/service/vector/request/QueryReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchIteratorReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1131 Sync 2.4 branch
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed

#1132 Return auto ids for InsertResp
  examples/main/java/io/milvus/v1/ClientPoolExample.java
  examples/main/java/io/milvus/v1/ConsistencyLevelExample.java
  examples/main/java/io/milvus/v1/JsonFieldExample.java
  examples/main/java/io/milvus/v1/ResourceGroupExample.java
  examples/main/java/io/milvus/v1/resourcegroup/NodeInfo.java
  examples/main/java/io/milvus/v1/resourcegroup/ResourceGroupInfo.java
  examples/main/java/io/milvus/v1/resourcegroup/ResourceGroupManagement.java
  examples/main/java/io/milvus/v2/BinaryVectorExample.java
  examples/main/java/io/milvus/v2/ClientPoolExample.java
  examples/main/java/io/milvus/v2/ConsistencyLevelExample.java
  examples/main/java/io/milvus/v2/Float16VectorExample.java
  examples/main/java/io/milvus/v2/GeneralExample.java
  examples/main/java/io/milvus/v2/HybridSearchExample.java
  examples/main/java/io/milvus/v2/IteratorExample.java
  examples/main/java/io/milvus/v2/JsonFieldExample.java
  examples/main/java/io/milvus/v2/SimpleExample.java
  examples/main/java/io/milvus/v2/SparseVectorExample.java
  examples/main/java/io/milvus/v2/TLSExample.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/response/InsertResp.java
Labels: lgtm, approved, ci-passed, size/XL

#1133 Return auto ids for InsertResp
  examples/main/java/io/milvus/v1/ClientPoolExample.java
  examples/main/java/io/milvus/v1/ConsistencyLevelExample.java
  examples/main/java/io/milvus/v1/JsonFieldExample.java
  examples/main/java/io/milvus/v1/ResourceGroupExample.java
  examples/main/java/io/milvus/v1/resourcegroup/NodeInfo.java
  examples/main/java/io/milvus/v1/resourcegroup/ResourceGroupInfo.java
  examples/main/java/io/milvus/v1/resourcegroup/ResourceGroupManagement.java
  examples/main/java/io/milvus/v2/BinaryVectorExample.java
  examples/main/java/io/milvus/v2/ClientPoolExample.java
  examples/main/java/io/milvus/v2/ConsistencyLevelExample.java
  examples/main/java/io/milvus/v2/Float16VectorExample.java
  examples/main/java/io/milvus/v2/GeneralExample.java
  examples/main/java/io/milvus/v2/HybridSearchExample.java
  examples/main/java/io/milvus/v2/IteratorExample.java
  examples/main/java/io/milvus/v2/JsonFieldExample.java
  examples/main/java/io/milvus/v2/SimpleExample.java
  examples/main/java/io/milvus/v2/SparseVectorExample.java
  examples/main/java/io/milvus/v2/TLSExample.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/response/InsertResp.java
Labels: lgtm, approved, ci-passed, size/XL

#1134 Fix a RpcDeadline bug for V2
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
Labels: size/L, lgtm, approved, ci-passed

#1135 Fix a RpcDeadline bug for V2
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
Labels: size/L, lgtm, approved, ci-passed

#1140 Prepare for v2.4.7
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1141 Prepare for v2.4.7
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1146 Fix setting data type for array of template expression
  examples/main/java/io/milvus/v2/SimpleExample.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1151 [cherry-pick] Fix setting data type for array of template expression
  examples/main/java/io/milvus/v2/SimpleExample.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1152 Fix dimension calculation bug for BinaryVector
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/QueryNodeSingleSearch.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1154 Fix dimension calculation bug for BinaryVector
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/QueryNodeSingleSearch.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1155 fix: add field schema info for descriptionCollection
  src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: size/XS

#1156 Fix a compatible bug for Gson 2.11.0+
  examples/main/java/io/milvus/v2/HybridSearchExample.java
  src/main/java/io/milvus/common/utils/JsonUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#1157 Fix a compatible bug for Gson 2.11.0+
  examples/main/java/io/milvus/v2/HybridSearchExample.java
  src/main/java/io/milvus/common/utils/JsonUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#1158 Add group size control for V1 and V2
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/HybridSearchParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/v2/service/vector/request/AnnSearchReq.java
  src/main/java/io/milvus/v2/service/vector/request/HybridSearchReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: size/L, lgtm, approved, ci-passed

#1159 Add group by field for hybridsearch
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/HybridSearchParam.java
  src/main/java/io/milvus/v2/service/vector/request/AnnSearchReq.java
  src/main/java/io/milvus/v2/service/vector/request/HybridSearchReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1160 Fix a null pointer bug of QueryIterator
  src/main/java/io/milvus/orm/iterator/IteratorAdapterV2.java
Labels: lgtm, approved, ci-passed, size/S

#1161 Fix a null pointer bug of QueryIterator
  src/main/java/io/milvus/orm/iterator/IteratorAdapterV2.java
Labels: lgtm, approved, ci-passed, size/S

#1162 Prepare for 2.4.8
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: approved, ci-passed, size/S

#1163 typo
  pom.xml
  src/main/java/io/milvus/param/dml/HybridSearchParam.java
Labels: lgtm, approved, ci-passed, size/XS
