Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-03, with the labels that each got.

#786 bug fix: set insert to null while upserting to prevent conflicting.
  src/main/java/io/milvus/v2/utils/DataUtils.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/GetCollectionStatsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/CreateIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/DeleteTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
Labels: lgtm, approved, ci-passed, size/S

#787 bug fix: set insert to null while upserting to prevent conflicting.
  src/main/java/io/milvus/v2/utils/DataUtils.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/GetCollectionStatsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/CreateIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/DeleteTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
Labels: ci-passed, size/S

#788 Add withDatabaseBame for releaseCollection
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/collection/ReleaseCollectionParam.java
Labels: lgtm, approved, ci-passed, size/M

#783 Use Testcontainers Milvus module
  pom.xml
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#791 [cherry-pick] Use Testcontainers Milvus module (#783)
  pom.xml
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#792 fix several bugs and add new parameter to support partition key.
  .gitignore
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/examples/Simple.java
  src/main/java/io/milvus/v2/examples/Simple_Schema.java
  src/main/java/io/milvus/v2/exception/ErrorCode.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/main/java/io/milvus/v2/service/collection/request/LoadCollectionReq.java
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/index/request/ListIndexesReq.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/request/GetReq.java
  src/main/java/io/milvus/v2/service/vector/request/QueryReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  src/main/java/io/milvus/v2/service/vector/response/QueryResp.java
  src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/main/java/io/milvus/v2/utils/SchemaUtils.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
  src/test/java/io/milvus/v2/service/collection/CollectionTest.java
Labels: size/L, lgtm, approved, ci-passed

#794 fix several bugs and add new parameter to support partition key. (#792)
  .gitignore
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/examples/Simple.java
  src/main/java/io/milvus/v2/examples/Simple_Schema.java
  src/main/java/io/milvus/v2/exception/ErrorCode.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/main/java/io/milvus/v2/service/collection/request/LoadCollectionReq.java
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/index/request/ListIndexesReq.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/request/GetReq.java
  src/main/java/io/milvus/v2/service/vector/request/QueryReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  src/main/java/io/milvus/v2/service/vector/response/QueryResp.java
  src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/main/java/io/milvus/v2/utils/SchemaUtils.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
  src/test/java/io/milvus/v2/service/collection/CollectionTest.java
Labels: size/L, ci-passed

#795 update default metricType to Cosine, and remove unnecessary call to reduce latency.
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: ci-passed, size/M

#801 [cherry-pick] Refine code
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/RpcStatus.java
  src/main/java/io/milvus/param/alias/AlterAliasParam.java
  src/main/java/io/milvus/param/alias/CreateAliasParam.java
  src/main/java/io/milvus/param/alias/DropAliasParam.java
  src/main/java/io/milvus/param/alias/ListAliasesParam.java
  src/main/java/io/milvus/param/bulkinsert/BulkInsertParam.java
  src/main/java/io/milvus/param/bulkinsert/GetBulkInsertStateParam.java
  src/main/java/io/milvus/param/bulkinsert/ListBulkInsertTasksParam.java
  src/main/java/io/milvus/param/collection/AlterCollectionParam.java
  src/main/java/io/milvus/param/collection/CreateDatabaseParam.java
  src/main/java/io/milvus/param/collection/DropCollectionParam.java
  src/main/java/io/milvus/param/collection/DropDatabaseParam.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/collection/FlushParam.java
  src/main/java/io/milvus/param/collection/GetCollectionStatisticsParam.java
  src/main/java/io/milvus/param/collection/GetLoadStateParam.java
  src/main/java/io/milvus/param/collection/GetLoadingProgressParam.java
  src/main/java/io/milvus/param/collection/ReleaseCollectionParam.java
  src/main/java/io/milvus/param/collection/RenameCollectionParam.java
  src/main/java/io/milvus/param/collection/ShowCollectionsParam.java
  src/main/java/io/milvus/param/control/GetCompactionPlansParam.java
  src/main/java/io/milvus/param/control/GetCompactionStateParam.java
  src/main/java/io/milvus/param/control/GetFlushAllStateParam.java
  src/main/java/io/milvus/param/control/GetFlushStateParam.java
  src/main/java/io/milvus/param/control/GetMetricsParam.java
  src/main/java/io/milvus/param/control/GetPersistentSegmentInfoParam.java
  src/main/java/io/milvus/param/control/GetQuerySegmentInfoParam.java
  src/main/java/io/milvus/param/control/GetReplicasParam.java
  src/main/java/io/milvus/param/control/LoadBalanceParam.java
  src/main/java/io/milvus/param/control/ManualCompactParam.java
  src/main/java/io/milvus/param/credential/CreateCredentialParam.java
  src/main/java/io/milvus/param/credential/DeleteCredentialParam.java
  src/main/java/io/milvus/param/credential/ListCredUsersParam.java
  src/main/java/io/milvus/param/credential/UpdateCredentialParam.java
  src/main/java/io/milvus/param/dml/DeleteParam.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/QueryParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/dml/UpsertParam.java
  src/main/java/io/milvus/param/index/DescribeIndexParam.java
  src/main/java/io/milvus/param/index/DropIndexParam.java
  src/main/java/io/milvus/param/index/GetIndexBuildProgressParam.java
  src/main/java/io/milvus/param/index/GetIndexStateParam.java
  src/main/java/io/milvus/param/partition/CreatePartitionParam.java
  src/main/java/io/milvus/param/partition/DropPartitionParam.java
  src/main/java/io/milvus/param/partition/GetPartitionStatisticsParam.java
  src/main/java/io/milvus/param/partition/HasPartitionParam.java
  src/main/java/io/milvus/param/partition/LoadPartitionsParam.java
  src/main/java/io/milvus/param/partition/ReleasePartitionsParam.java
  src/main/java/io/milvus/param/partition/ShowPartitionsParam.java
  src/main/java/io/milvus/param/resourcegroup/CreateResourceGroupParam.java
  src/main/java/io/milvus/param/resourcegroup/DescribeResourceGroupParam.java
  src/main/java/io/milvus/param/resourcegroup/DropResourceGroupParam.java
  src/main/java/io/milvus/param/resourcegroup/ListResourceGroupsParam.java
  src/main/java/io/milvus/param/resourcegroup/TransferNodeParam.java
  src/main/java/io/milvus/param/resourcegroup/TransferReplicaParam.java
  src/main/java/io/milvus/param/role/SelectGrantForRoleParam.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
Labels: lgtm, size/XXL, approved, ci-passed

#802 Modify testcases for java-sdk v2
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/CreateCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/GetCollectionStatsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/ListIndexesTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/LoadPartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/ReleasePartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/GrantPrivilegeTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/DeleteTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/QueryTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
Labels: size/L, lgtm, ci-passed

#803 [cherry-pick]Modify testcases for java-sdk v2
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/CreateCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/GetCollectionStatsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/ListIndexesTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/LoadPartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/ReleasePartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/GrantPrivilegeTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/DeleteTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/QueryTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
Labels: size/L, lgtm, ci-passed

#797 Support BulkWriter
  examples/main/java/io/milvus/BulkWriterExample.java
  examples/main/resources/data/train_embeddings.csv
  pom.xml
  src/main/java/io/milvus/bulkwriter/Buffer.java
  src/main/java/io/milvus/bulkwriter/BulkWriter.java
  src/main/java/io/milvus/bulkwriter/CloudImport.java
  src/main/java/io/milvus/bulkwriter/LocalBulkWriter.java
  src/main/java/io/milvus/bulkwriter/LocalBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriter.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/BulkFileType.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/CloudStorage.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/TypeSize.java
  src/main/java/io/milvus/bulkwriter/common/utils/GeneratorUtils.java
  src/main/java/io/milvus/bulkwriter/common/utils/ImportUtils.java
  src/main/java/io/milvus/bulkwriter/common/utils/ParquetReaderUtils.java
  src/main/java/io/milvus/bulkwriter/common/utils/ParquetUtils.java
  src/main/java/io/milvus/bulkwriter/connect/AzureConnectParam.java
  src/main/java/io/milvus/bulkwriter/connect/S3ConnectParam.java
  src/main/java/io/milvus/bulkwriter/connect/StorageConnectParam.java
  src/main/java/io/milvus/bulkwriter/response/BulkImportResponse.java
  src/main/java/io/milvus/bulkwriter/response/GetImportProgressResponse.java
  src/main/java/io/milvus/bulkwriter/response/ListImportJobsResponse.java
  src/main/java/io/milvus/bulkwriter/response/RestfulResponse.java
  src/main/java/io/milvus/bulkwriter/storage/StorageClient.java
  src/main/java/io/milvus/bulkwriter/storage/client/AzureStorageClient.java
  src/main/java/io/milvus/bulkwriter/storage/client/MinioStorageClient.java
  src/main/java/io/milvus/common/utils/ExceptionUtils.java
  src/main/java/io/milvus/exception/UnExpectedException.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/collection/CollectionSchemaParam.java
  src/main/java/io/milvus/param/collection/CreateCollectionParam.java
  src/main/java/io/milvus/response/DescCollResponseWrapper.java
Labels: lgtm, size/XXL, approved, ci-passed

#804 [cherry-pick] Support bulkWriter
  examples/main/java/io/milvus/BulkWriterExample.java
  examples/main/resources/data/train_embeddings.csv
  pom.xml
  src/main/java/io/milvus/bulkwriter/Buffer.java
  src/main/java/io/milvus/bulkwriter/BulkWriter.java
  src/main/java/io/milvus/bulkwriter/CloudImport.java
  src/main/java/io/milvus/bulkwriter/LocalBulkWriter.java
  src/main/java/io/milvus/bulkwriter/LocalBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriter.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/BulkFileType.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/CloudStorage.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/TypeSize.java
  src/main/java/io/milvus/bulkwriter/common/utils/GeneratorUtils.java
  src/main/java/io/milvus/bulkwriter/common/utils/ImportUtils.java
  src/main/java/io/milvus/bulkwriter/common/utils/ParquetReaderUtils.java
  src/main/java/io/milvus/bulkwriter/common/utils/ParquetUtils.java
  src/main/java/io/milvus/bulkwriter/connect/AzureConnectParam.java
  src/main/java/io/milvus/bulkwriter/connect/S3ConnectParam.java
  src/main/java/io/milvus/bulkwriter/connect/StorageConnectParam.java
  src/main/java/io/milvus/bulkwriter/response/BulkImportResponse.java
  src/main/java/io/milvus/bulkwriter/response/GetImportProgressResponse.java
  src/main/java/io/milvus/bulkwriter/response/ListImportJobsResponse.java
  src/main/java/io/milvus/bulkwriter/response/RestfulResponse.java
  src/main/java/io/milvus/bulkwriter/storage/StorageClient.java
  src/main/java/io/milvus/bulkwriter/storage/client/AzureStorageClient.java
  src/main/java/io/milvus/bulkwriter/storage/client/MinioStorageClient.java
  src/main/java/io/milvus/common/utils/ExceptionUtils.java
  src/main/java/io/milvus/exception/UnExpectedException.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/collection/CollectionSchemaParam.java
  src/main/java/io/milvus/param/collection/CreateCollectionParam.java
  src/main/java/io/milvus/response/DescCollResponseWrapper.java
Labels: lgtm, size/XXL, approved, ci-passed

#807 add bulkwrite testcase
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/bulk/BulkWriteTest.java
Labels: size/L, lgtm, approved, ci-passed

#809 add bulkWrite testcase
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/bulk/BulkWriteTest.java
Labels: size/L, lgtm, approved, ci-passed

#812 Support BFloat16/Float16 vector
  README.md
  docker-compose.yml
  examples/main/java/io/milvus/Float16Example.java
  examples/pom.xml
  pom.xml
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/QueryNodeSingleSearch.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/highlevel/dml/SearchSimpleParam.java
  src/main/java/io/milvus/response/DescCollResponseWrapper.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/v2/utils/DataUtils.java
Labels: size/L, lgtm, approved, ci-passed

#815 add remote bulkwrite and cloud import case
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/BaseCloudTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/bulkimport/BulkImportTest.java
Labels: size/L, lgtm, approved, ci-passed

#816 add remote bulkwrite and cloud import case
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/BaseCloudTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/bulk/BulkWriteTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/bulkimport/BulkImportTest.java
  tests/milvustest/src/test/java/resources/run.properties
Labels: lgtm, approved, ci-passed, size/XL

#817 fix CVE-2023-3635
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#818 [cherry-pick] fix CVE-2023-3635
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#811 bug fix: retry search while error code is 2200.
  src/main/java/io/milvus/v2/service/vector/VectorService.java
Labels: lgtm, approved, ci-passed, size/XS

#819 add retry count for search, if retry for more than five times, throw exception.
  src/main/java/io/milvus/v2/service/vector/VectorService.java
Labels: size/XS

#821 Upgrade the third-party package version to fix the cve problem
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#822 [cherry-pick]Upgrade the third-party package version to fix the cve problem
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#823 Fix TC Storage UnknownHostException
  pom.xml
  src/main/java/io/milvus/bulkwriter/common/clientenum/CloudStorage.java
Labels: lgtm, approved, ci-passed, size/XS

#824 [cherry-pick] Fix TC Storage UnknownHostException
  pom.xml
  src/main/java/io/milvus/bulkwriter/common/clientenum/CloudStorage.java
Labels: lgtm, approved, ci-passed, size/XS

#826 downgrade mockito version to work with java8 and remove retry for search
  pom.xml
  src/main/java/io/milvus/v2/exception/ErrorCode.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
Labels: lgtm, approved, ci-passed, size/S

#825 downgrade mockito version to 4.11.0 to make it compatible with Java 8, and remove retry for search
  pom.xml
  src/main/java/io/milvus/v2/exception/ErrorCode.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
Labels: lgtm, approved, ci-passed, size/S

#829 Fix a retry bug
  src/main/java/io/milvus/client/MilvusServiceClient.java
Labels: lgtm, approved, ci-passed, size/S

#830 Fix a retry bug
  src/main/java/io/milvus/client/MilvusServiceClient.java
Labels: lgtm, approved, ci-passed, size/S

#835 Add missed methods for retry
  src/main/java/io/milvus/client/MilvusServiceClient.java
Labels: lgtm, approved, ci-passed, size/M

#836 [Cherry-pick] Add missed methods for retry
  src/main/java/io/milvus/client/MilvusServiceClient.java
Labels: lgtm, approved, ci-passed, size/M

#834 [cherry-pick] Fix bulkWriter example
  examples/main/java/io/milvus/BulkWriterExample.java
  pom.xml
  src/main/java/io/milvus/bulkwriter/common/clientenum/CloudStorage.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/bulkimport/BulkImportTest.java
Labels: lgtm, approved, ci-passed, size/S
