Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-12, with the labels that each got.

#1204 Update Float16VectorExample.java (#1203)
  examples/main/java/io/milvus/v2/Float16VectorExample.java
Labels: lgtm, approved, ci-passed, size/S

#1205 Update Float16VectorExample.java (#1203)
  examples/main/java/io/milvus/v2/Float16VectorExample.java
Labels: lgtm, approved, ci-passed, size/S

#1207 remove auto-id check for upsert as it's supported now
  src/main/java/io/milvus/v2/utils/DataUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#1210 Fix a bug of V2 that dynamic values not inserted
  src/main/java/io/milvus/v2/utils/SchemaUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1211 Fix a bug of V2 that dynamic values not inserted
  src/main/java/io/milvus/v2/utils/SchemaUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1213 Remove auto-id check for upsert for V2
  src/main/java/io/milvus/v2/utils/DataUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#1214 Remove auto-id check for upsert for V2
  src/main/java/io/milvus/v2/utils/DataUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#1215 Prepare for v2.5.1
  CHANGELOG.md
  README.md
  examples/main/java/io/milvus/v2/BulkWriterExample.java
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1216 Prepare for v2.5.1
  CHANGELOG.md
  README.md
  examples/main/java/io/milvus/v2/BulkWriterExample.java
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1220 Fix a bug of listPrivilegeGroups
  src/main/java/io/milvus/v2/service/rbac/RBACService.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1221 Fix a bug of listPrivilegeGroups
  src/main/java/io/milvus/v2/service/rbac/RBACService.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1222 Fix a bug of listPrivilegeGroups
  src/main/java/io/milvus/v2/service/rbac/RBACService.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1225 Fix a deploy bug
  examples/pom.xml
  pom.xml
  sdk-bulkwriter/pom.xml
  sdk-core/pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1226 Fix a deploy bug
  examples/pom.xml
  pom.xml
  sdk-bulkwriter/pom.xml
  sdk-core/pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1227 Prepare for v2.5.2
  CHANGELOG.md
  examples/pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#1228 Prepare for v2.5.2
  CHANGELOG.md
  examples/pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#1229 DescribeRoleReq support dbName parameter
  sdk-core/src/main/java/io/milvus/v2/service/rbac/RBACService.java
  sdk-core/src/main/java/io/milvus/v2/service/rbac/request/DescribeRoleReq.java
Labels: lgtm, approved, ci-passed, size/S

#1230 [cherry-pick] DescribeRoleReq support dbName parameter
  sdk-core/src/main/java/io/milvus/v2/service/rbac/RBACService.java
  sdk-core/src/main/java/io/milvus/v2/service/rbac/request/DescribeRoleReq.java
Labels: lgtm, approved, ci-passed, size/S

#1233 RevokeRolePrivilegeParam support dbName parameter
  sdk-core/src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  sdk-core/src/main/java/io/milvus/param/role/RevokeRolePrivilegeParam.java
Labels: lgtm, approved, ci-passed, size/M

#1234 [cherry-pick] RevokeRolePrivilegeParam support dbName parameter
  sdk-core/src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  sdk-core/src/main/java/io/milvus/param/role/RevokeRolePrivilegeParam.java
Labels: lgtm, approved, ci-passed, size/M

#1243 Add RefreshLoad/GetPartitionStats interface
  examples/main/java/io/milvus/v2/BulkWriterExample.java
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/RefreshLoadReq.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/PartitionService.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/request/GetPartitionStatsReq.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/response/GetPartitionStatsResp.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/UtilityService.java
Labels: size/L, lgtm, approved, ci-passed

#1244 Add RefreshLoad/GetPartitionStats interface
  examples/main/java/io/milvus/v2/BulkWriterExample.java
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/RefreshLoadReq.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/PartitionService.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/request/GetPartitionStatsReq.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/response/GetPartitionStatsResp.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/UtilityService.java
Labels: size/L, lgtm, approved, ci-passed

#1245 Add RefreshLoad/GetPartitionStats interface
  examples/main/java/io/milvus/v2/BulkWriterExample.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/RefreshLoadReq.java
  src/main/java/io/milvus/v2/service/partition/PartitionService.java
  src/main/java/io/milvus/v2/service/partition/request/GetPartitionStatsReq.java
  src/main/java/io/milvus/v2/service/partition/response/GetPartitionStatsResp.java
  src/main/java/io/milvus/v2/service/utility/UtilityService.java
Labels: size/L, lgtm, approved, ci-passed

#1247 Flatten search params
  sdk-core/src/main/java/io/milvus/param/Constant.java
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: size/L, lgtm, approved, ci-passed

#1248 Support resource groups for loadCollection/loadPartition
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/LoadCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/PartitionService.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/request/LoadPartitionsReq.java
Labels: lgtm, approved, ci-passed, size/XS

#1249 Support resource groups for loadCollection/loadPartition
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/LoadCollectionReq.java
  src/main/java/io/milvus/v2/service/partition/PartitionService.java
  src/main/java/io/milvus/v2/service/partition/request/LoadPartitionsReq.java
Labels: lgtm, approved, ci-passed, size/XS

#1250 Support resource groups for loadCollection/loadPartition
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/LoadCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/PartitionService.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/request/LoadPartitionsReq.java
Labels: lgtm, approved, ci-passed, size/XS

#1251 Support AlterCollectionField
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/AlterCollectionFieldReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1252 Support AlterCollectionField
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/AlterCollectionFieldReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1253 Support AlterCollectionField
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/AlterCollectionFieldReq.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1254 ResourceGroup interfaces for V2
  sdk-core/src/main/java/io/milvus/common/resourcegroup/NodeInfo.java
  sdk-core/src/main/java/io/milvus/common/resourcegroup/ResourceGroupConfig.java
  sdk-core/src/main/java/io/milvus/common/resourcegroup/ResourceGroupLimit.java
  sdk-core/src/main/java/io/milvus/common/resourcegroup/ResourceGroupNodeFilter.java
  sdk-core/src/main/java/io/milvus/common/resourcegroup/ResourceGroupTransfer.java
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/ResourceGroupService.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/CreateResourceGroupReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/DescribeResourceGroupReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/DropResourceGroupReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/ListResourceGroupsReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/TransferReplicaReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/UpdateResourceGroupsReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/response/DescribeResourceGroupResp.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/response/ListResourceGroupsResp.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1255 ResourceGroup interfaces for V2
  sdk-core/src/main/java/io/milvus/common/resourcegroup/NodeInfo.java
  sdk-core/src/main/java/io/milvus/common/resourcegroup/ResourceGroupConfig.java
  sdk-core/src/main/java/io/milvus/common/resourcegroup/ResourceGroupLimit.java
  sdk-core/src/main/java/io/milvus/common/resourcegroup/ResourceGroupNodeFilter.java
  sdk-core/src/main/java/io/milvus/common/resourcegroup/ResourceGroupTransfer.java
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/ResourceGroupService.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/CreateResourceGroupReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/DescribeResourceGroupReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/DropResourceGroupReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/ListResourceGroupsReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/TransferReplicaReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/UpdateResourceGroupsReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/response/DescribeResourceGroupResp.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/response/ListResourceGroupsResp.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1256 ResourceGroup interfaces for V2
  src/main/java/io/milvus/common/resourcegroup/NodeInfo.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupConfig.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupLimit.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupNodeFilter.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupTransfer.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/resourcegroup/ResourceGroupService.java
  src/main/java/io/milvus/v2/service/resourcegroup/request/CreateResourceGroupReq.java
  src/main/java/io/milvus/v2/service/resourcegroup/request/DescribeResourceGroupReq.java
  src/main/java/io/milvus/v2/service/resourcegroup/request/DropResourceGroupReq.java
  src/main/java/io/milvus/v2/service/resourcegroup/request/ListResourceGroupsReq.java
  src/main/java/io/milvus/v2/service/resourcegroup/request/TransferReplicaReq.java
  src/main/java/io/milvus/v2/service/resourcegroup/request/UpdateResourceGroupsReq.java
  src/main/java/io/milvus/v2/service/resourcegroup/response/DescribeResourceGroupResp.java
  src/main/java/io/milvus/v2/service/resourcegroup/response/ListResourceGroupsResp.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1257 Clean schema cache when switch database
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1258 Clean schema cache when switch database
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1259 Clean schema cache when switch database
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1262 Support database name for bulkimport
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/CloudImportRequest.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
Labels: lgtm, approved, ci-passed, size/XS

#1264 Support database name for bulkimport
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/CloudImportRequest.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
Labels: lgtm, approved, ci-passed, size/XS

#1263 Support database name for bulkimport
  src/main/java/io/milvus/bulkwriter/request/import_/CloudImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
Labels: lgtm, approved, ci-passed, size/XS

#1265 Refine code
  examples/main/java/io/milvus/v1/IteratorExample.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/CloudImportRequest.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
  sdk-core/src/main/java/io/milvus/common/resourcegroup/ResourceGroupConfig.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/TransferReplicaReq.java
Labels: lgtm, approved, ci-passed, size/M

#1266 Refine code
  examples/main/java/io/milvus/v1/IteratorExample.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/CloudImportRequest.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
  sdk-core/src/main/java/io/milvus/common/resourcegroup/ResourceGroupConfig.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/TransferReplicaReq.java
Labels: lgtm, approved, ci-passed, size/M

#1267 Refine code
  examples/main/java/io/milvus/v1/IteratorExample.java
  src/main/java/io/milvus/bulkwriter/request/import_/CloudImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupConfig.java
  src/main/java/io/milvus/v2/service/resourcegroup/request/TransferReplicaReq.java
Labels: lgtm, approved, ci-passed, size/M

#1268 QueryIterator/SearchIterator support retry
  sdk-core/src/main/java/io/milvus/orm/iterator/QueryIterator.java
  sdk-core/src/main/java/io/milvus/orm/iterator/SearchIterator.java
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/utils/RpcUtils.java
Labels: size/L, lgtm, approved, ci-passed

#1269 QueryIterator/SearchIterator support retry
  sdk-core/src/main/java/io/milvus/orm/iterator/QueryIterator.java
  sdk-core/src/main/java/io/milvus/orm/iterator/SearchIterator.java
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/utils/RpcUtils.java
Labels: size/L, lgtm, approved, ci-passed

#1270 QueryIterator/SearchIterator support retry
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/utils/RpcUtils.java
Labels: size/L, lgtm, approved, ci-passed

#1271 Enable dbName for bulkimport
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/CloudImportRequest.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
Labels: lgtm, approved, ci-passed, size/XS

#1272 Enable dbName for bulkimport
  src/main/java/io/milvus/bulkwriter/request/import_/CloudImportRequest.java
  src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
Labels: lgtm, approved, ci-passed, size/XS

#1273 Enable dbName for bulkimport
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/CloudImportRequest.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/MilvusImportRequest.java
Labels: lgtm, approved, ci-passed, size/XS

#1274 Prepare for v2.5.3
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1275 Prepare for v2.5.3
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1276 Prepare for v2.4.10
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S
