Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-11, with the labels that each got.

#1167 modify alterindex test
  tests/milvustestv2/pom.xml
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/AlterIndexTest.java
Labels: lgtm, approved, ci-passed, size/XS

#1164 fix: unused `buf2` in `v2/Float16VectorExample.java` example
  examples/main/java/io/milvus/v2/Float16VectorExample.java
Labels: lgtm, approved, ci-passed, size/XS

#1166 fix: unused `buf2` in `v2/Float16VectorExample.java` example
  examples/main/java/io/milvus/v2/Float16VectorExample.java
Labels: lgtm, approved, ci-passed, size/XS

#1169 Client throw exception if failed to get client
  src/main/java/io/milvus/pool/ClientPool.java
Labels: lgtm, approved, ci-passed, size/XS

#1170 Client throw exception if failed to get client
  src/main/java/io/milvus/pool/ClientPool.java
Labels: lgtm, approved, ci-passed, size/XS

#1173 Client pool throw exception if failed to create client
  src/main/java/io/milvus/pool/PoolClientFactory.java
Labels: lgtm, approved, ci-passed, size/XS

#1178 Fix an unstable test issue
  docker-compose.yml
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1179 Iterator mvcc
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/HybridSearchParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/request/HybridSearchReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  src/main/java/io/milvus/v2/service/vector/response/QueryResp.java
  src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1181 Support doc in doc out
  .attach_pid4051998
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/request/data/EmbeddedText.java
  src/main/java/io/milvus/v2/utils/DataUtils.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1185 Add RBAC enhancement interfaces for V2
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/rbac/Privilege.java
  src/main/java/io/milvus/v2/service/rbac/PrivilegeGroup.java
  src/main/java/io/milvus/v2/service/rbac/RBACService.java
  src/main/java/io/milvus/v2/service/rbac/RoleService.java
  src/main/java/io/milvus/v2/service/rbac/UserService.java
  src/main/java/io/milvus/v2/service/rbac/request/AddPrivilegesToGroupReq.java
  src/main/java/io/milvus/v2/service/rbac/request/CreatePrivilegeGroupReq.java
  src/main/java/io/milvus/v2/service/rbac/request/DropPrivilegeGroupReq.java
  src/main/java/io/milvus/v2/service/rbac/request/ListPrivilegeGroupsReq.java
  src/main/java/io/milvus/v2/service/rbac/request/RemovePrivilegesFromGroupReq.java
  src/main/java/io/milvus/v2/service/rbac/response/ListPrivilegeGroupsResp.java
Labels: lgtm, approved, ci-passed, size/XL

#1186 Add RBAC enhancement interfaces for V2
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/rbac/Privilege.java
  src/main/java/io/milvus/v2/service/rbac/PrivilegeGroup.java
  src/main/java/io/milvus/v2/service/rbac/RBACService.java
  src/main/java/io/milvus/v2/service/rbac/RoleService.java
  src/main/java/io/milvus/v2/service/rbac/UserService.java
  src/main/java/io/milvus/v2/service/rbac/request/AddPrivilegesToGroupReq.java
  src/main/java/io/milvus/v2/service/rbac/request/CreatePrivilegeGroupReq.java
  src/main/java/io/milvus/v2/service/rbac/request/DropPrivilegeGroupReq.java
  src/main/java/io/milvus/v2/service/rbac/request/ListPrivilegeGroupsReq.java
  src/main/java/io/milvus/v2/service/rbac/request/RemovePrivilegesFromGroupReq.java
  src/main/java/io/milvus/v2/service/rbac/response/ListPrivilegeGroupsResp.java
Labels: lgtm, approved, ci-passed, size/XL

#1191 add default port and support dbname for uri, 19530 by default, 443 for serverless
  src/main/java/io/milvus/v2/client/ConnectConfig.java
Labels: lgtm, approved, ci-passed, size/S

#1192 [cherry-pick] add default port and support dbname for uri, 19530 by default, 443 for serverless
  src/main/java/io/milvus/v2/client/ConnectConfig.java
Labels: lgtm, approved, ci-passed, size/S

#1193 BulkWriter supports Json/CSV
  examples/main/java/io/milvus/v2/SimpleExample.java
  src/main/java/io/milvus/bulkwriter/Buffer.java
  src/main/java/io/milvus/bulkwriter/LocalBulkWriter.java
  src/main/java/io/milvus/bulkwriter/LocalBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriter.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/BulkFileType.java
  src/test/java/io/milvus/TestUtils.java
  src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#1194 BulkWriter supports Json
  src/main/java/io/milvus/bulkwriter/Buffer.java
  src/main/java/io/milvus/bulkwriter/LocalBulkWriter.java
  src/main/java/io/milvus/bulkwriter/LocalBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriter.java
  src/main/java/io/milvus/bulkwriter/RemoteBulkWriterParam.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/BulkFileType.java
  src/test/java/io/milvus/TestUtils.java
  src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1195 Prepare for 2.5.0
  CHANGELOG.md
  README.md
  docker-compose.yml
  examples/pom.xml
  pom.xml
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1196 Prepare for 2.5.0
  CHANGELOG.md
  README.md
  docker-compose.yml
  examples/pom.xml
  pom.xml
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1197 Prepare for 2.4.9
  CHANGELOG.md
  README.md
  docker-compose.yml
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1198 Show expression template example
  examples/main/java/io/milvus/v2/SimpleExample.java
Labels: lgtm, approved, ci-passed, size/M

#1203 Update Float16VectorExample.java
  examples/main/java/io/milvus/v2/Float16VectorExample.java
Labels: lgtm, approved, ci-passed, size/S
