Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-04, with the labels that each got.

#831 Support sparse vector
  examples/main/java/io/milvus/BinaryVectorExample.java
  examples/main/java/io/milvus/Float16VectorExample.java
  examples/main/java/io/milvus/SparseVectorExample.java
  src/main/java/io/milvus/param/IndexType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/QueryNodeSingleSearch.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/param/dml/InsertParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/main/java/io/milvus/response/basic/RowRecordWrapper.java
  src/main/java/io/milvus/v2/utils/DataUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#839 Add new index types and groupby field for search
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/IndexType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/SearchParam.java
Labels: lgtm, approved, ci-passed, size/S

#843 add new index type for v2 client: INVERTED, GPU_CAGRA, sparse vector …
  src/main/java/io/milvus/v2/common/IndexParam.java
Labels: lgtm, approved, ci-passed, size/S

#847 Set example package name
  examples/main/java/io/milvus/BinaryVectorExample.java
  examples/main/java/io/milvus/BulkWriterExample.java
  examples/main/java/io/milvus/CommonUtils.java
  examples/main/java/io/milvus/Float16VectorExample.java
  examples/main/java/io/milvus/GeneralExample.java
  examples/main/java/io/milvus/HighLevelExample.java
  examples/main/java/io/milvus/HybridSearchExample.java
  examples/main/java/io/milvus/RBACExample.java
  examples/main/java/io/milvus/SimpleExample.java
  examples/main/java/io/milvus/SparseVectorExample.java
  examples/main/java/io/milvus/TLSExample.java
Labels: lgtm, approved, ci-passed, size/S

#848 Explicitly specify vector type when search
  examples/main/java/io/milvus/BinaryVectorExample.java
  examples/main/java/io/milvus/Float16VectorExample.java
  examples/main/java/io/milvus/GeneralExample.java
  examples/main/java/io/milvus/HybridSearchExample.java
  examples/main/java/io/milvus/SimpleExample.java
  examples/main/java/io/milvus/SparseVectorExample.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/dml/AnnSearchParam.java
  src/main/java/io/milvus/param/dml/HybridSearchParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/index/AlterIndexParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#849 Refine example code
  examples/main/java/io/milvus/CommonUtils.java
  examples/main/java/io/milvus/GeneralExample.java
  examples/main/java/io/milvus/HighLevelExample.java
Labels: size/L, lgtm, approved, ci-passed

#850 Refine example code
  examples/main/java/io/milvus/HybridSearchExample.java
  src/main/java/io/milvus/param/dml/AnnSearchParam.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/param/highlevel/dml/SearchSimpleParam.java
Labels: size/L, lgtm, approved, ci-passed

#846 support searchIterator && queryIterator
  examples/main/java/io/milvus/CommonUtils.java
  examples/main/java/io/milvus/IteratorExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/orm/iterator/IteratorCache.java
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/dml/QueryIteratorParam.java
  src/main/java/io/milvus/param/dml/SearchIteratorParam.java
Labels: lgtm, size/XXL, approved, ci-passed

#851 support searchIterator && queryIterator
  examples/main/java/io/milvus/CommonUtils.java
  examples/main/java/io/milvus/IteratorExample.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/orm/iterator/IteratorCache.java
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/dml/QueryIteratorParam.java
  src/main/java/io/milvus/param/dml/SearchIteratorParam.java
Labels: lgtm, size/XXL, approved, ci-passed

#853 [cherry-pick] upgrade hadoop-client version
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#857 searchIterator support multi vector type
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/param/dml/SearchIteratorParam.java
Labels: size/L, lgtm, approved, ci-passed

#855 set secure default to false and true if uri starts with https
  src/main/java/io/milvus/v2/client/ConnectConfig.java
Labels: lgtm, ci-passed, size/S

#858 set secure default to false and true if uri starts with https
  src/main/java/io/milvus/v2/client/ConnectConfig.java
Labels: lgtm, approved, ci-passed, size/S

#859 fix: Revert "enhance: add resource group declarative api (#755)"
  examples/main/java/io/milvus/ResourceGroupExample.java
  examples/main/java/io/milvus/resourcegroup/NodeInfo.java
  examples/main/java/io/milvus/resourcegroup/ResourceGroupInfo.java
  examples/main/java/io/milvus/resourcegroup/ResourceGroupManagement.java
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupConfig.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupLimit.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupTransfer.java
  src/main/java/io/milvus/param/control/GetReplicasParam.java
  src/main/java/io/milvus/param/resourcegroup/CreateResourceGroupParam.java
  src/main/java/io/milvus/param/resourcegroup/UpdateResourceGroupsParam.java
Labels: lgtm, approved, ci-passed, size/XL

#861 Connection initialize
  examples/pom.xml
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupConfig.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  src/test/java/io/milvus/server/MockMilvusServerImpl.java
Labels: size/L, lgtm, approved, ci-passed

#862 Connection initialize
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  src/test/java/io/milvus/server/MockMilvusServerImpl.java
Labels: size/L, lgtm, approved, ci-passed

#863 Connection initialize
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/ConnectParam.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
  src/test/java/io/milvus/server/MockMilvusServerImpl.java
Labels: size/L, lgtm, approved, ci-passed

#865 Prepare for v2.3.6
  CHANGELOG.md
  README.md
  docker-compose.yml
  examples/main/java/io/milvus/BulkWriterExample.java
  examples/main/java/io/milvus/IteratorExample.java
  examples/pom.xml
  pom.xml
  src/main/java/io/milvus/param/ConnectParam.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#869 bulkWriter support local MinioStorage
  examples/main/java/io/milvus/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/CloudStorage.java
Labels: lgtm, approved, ci-passed, size/S

#870 bulkWriter support local MinioStorage
  examples/main/java/io/milvus/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/CloudStorage.java
Labels: lgtm, approved, ci-passed, size/S

#871 bulkWriter support local MinioStorage
  examples/main/java/io/milvus/BulkWriterExample.java
  src/main/java/io/milvus/bulkwriter/common/clientenum/CloudStorage.java
Labels: lgtm, approved, ci-passed, size/S

#873 Update readme
  CHANGELOG.md
  README.md
Labels: lgtm, approved, ci-passed, size/S

#874 Update readme
  CHANGELOG.md
  README.md
Labels: lgtm, approved, ci-passed, size/S

#875 add or modify testcases for 2.4
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/BaseCloudTest.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/MathUtil.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/bulk/BulkWriteTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/bulkimport/BulkImportTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/CreateCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/compaction/ManualCompactionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/database/DatabaseTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/IndexLoadTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/DeleteTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/UpsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/mmap/AlterCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/mmap/AlterIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/MultipleArraysDataFactory.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryIteratorTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/RangeSearchTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchIteratorTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/segment/GetQuerySegmentInfoTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#876 [cherry-pick] add or modify testcases for 2.4 (#875)
  tests/milvustest/pom.xml
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/BaseCloudTest.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonData.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/common/CommonFunction.java
  tests/milvustest/src/main/java/com/zilliz/milvustest/util/MathUtil.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/bulk/BulkWriteTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/bulkimport/BulkImportTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/collection/CreateCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/compaction/ManualCompactionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/database/DatabaseTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/CreateIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/index/IndexLoadTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/DeleteTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/InsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/insert/UpsertTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/mmap/AlterCollectionTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/mmap/AlterIndexTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/MultipleArraysDataFactory.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryIteratorTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/query/QueryTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/RangeSearchTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchIteratorTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/search/SearchTest.java
  tests/milvustest/src/test/java/com/zilliz/milvustest/segment/GetQuerySegmentInfoTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#879 [Cherry-Pick] enhance: add resource group declarative api
  examples/main/java/io/milvus/ResourceGroupExample.java
  examples/main/java/io/milvus/resourcegroup/NodeInfo.java
  examples/main/java/io/milvus/resourcegroup/ResourceGroupInfo.java
  examples/main/java/io/milvus/resourcegroup/ResourceGroupManagement.java
  examples/pom.xml
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupConfig.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupLimit.java
  src/main/java/io/milvus/common/resourcegroup/ResourceGroupTransfer.java
  src/main/java/io/milvus/param/control/GetReplicasParam.java
  src/main/java/io/milvus/param/resourcegroup/CreateResourceGroupParam.java
  src/main/java/io/milvus/param/resourcegroup/UpdateResourceGroupsParam.java
Labels: lgtm, approved, ci-passed, size/XL
