Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-02, with the labels that each got.

#750 search interface support not specify metricType
  src/main/java/io/milvus/param/MetricType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/QueryNodeSingleSearch.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/response/DescIndexResponseWrapper.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#752 merge CreateCollectionWithSchemaReq.java with CreateCollectionReq to …
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/common/ConsistencyLevel.java
  src/main/java/io/milvus/v2/examples/Simple_Schema.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionWithSchemaReq.java
  src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
  src/main/java/io/milvus/v2/utils/SchemaUtils.java
  src/test/java/io/milvus/v2/service/collection/CollectionTest.java
Labels: size/L, ci-passed

#754 Update describeAlias to use request
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/utility/UtilityService.java
  src/main/java/io/milvus/v2/service/utility/request/DescribeAliasReq.java
  src/test/java/io/milvus/v2/service/utility/UtilityTest.java
Labels: size/M

#757 Fix a bug of SearchResutsWrapper
  src/main/java/io/milvus/response/SearchResultsWrapper.java
Labels: lgtm, approved, ci-passed, size/S

#758 Fix a bug of SearchResutsWrapper
  src/main/java/io/milvus/response/SearchResultsWrapper.java
Labels: lgtm, approved, ci-passed, size/S

#776 add java-sdk-v2 testcase
  tests/milvustestv2/.gitignore
  tests/milvustestv2/pom.xml
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/Milvustestv2Application.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/BaseTest.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonData.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/config/ConnectInfoConfig.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/listener/CustomerListener.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/utils/FileUtils.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/utils/GenerateUtil.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/utils/HttpClientUtils.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/utils/PropertyFilesUtil.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/Milvustestv2ApplicationTests.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/AlterAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/CreateAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/DescribeAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/DropAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/ListAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/CreateCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/DescribeCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/DropCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/GetCollectionStatsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/HasCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/ListCollectionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/RenameCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/CreateIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/DescribeIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/DropIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/ListIndexesTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/LoadCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/LoadPartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/ReleaseCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/ReleasePartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/partition/CreatePartitionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/partition/DropPartitionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/partition/HasPartitionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/partition/ListPartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/CreateRoleTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/CreateUserTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/DescribeRoleTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/DescribeUserTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/DropRoleTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/DropUserTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/GrantPrivilegeTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/GrantRoleTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/ListRolesTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/ListUsersTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/RevokePrivilegeTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/RevokeRoleTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/UpdatePasswordTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/DeleteTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/GetTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/InsertTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/QueryTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/UpsertTest.java
  tests/milvustestv2/src/test/resources/run.properties
  tests/milvustestv2/src/test/resources/testdata/db_admin.json
  tests/milvustestv2/src/test/resources/testdata/privilege.json
  tests/milvustestv2/testng.xml
Labels: size/XXL

#780 set secure to false if token is null or empty and fix unit test
  src/main/java/io/milvus/v2/client/ConnectConfig.java
  src/test/java/io/milvus/v2/BaseTest.java
  src/test/java/io/milvus/v2/service/collection/CollectionTest.java
Labels: lgtm, approved, ci-passed, size/S

#781 set secure to false if token is null or empty and fix unit test
  src/main/java/io/milvus/v2/client/ConnectConfig.java
  src/test/java/io/milvus/v2/BaseTest.java
  src/test/java/io/milvus/v2/service/collection/CollectionTest.java
Labels: lgtm, approved, ci-passed, size/S

#779 add java-sdk v2 testcases
  tests/milvustestv2/.gitignore
  tests/milvustestv2/pom.xml
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/Milvustestv2Application.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/BaseTest.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonData.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/config/ConnectInfoConfig.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/listener/CustomerListener.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/utils/FileUtils.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/utils/GenerateUtil.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/utils/HttpClientUtils.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/utils/PropertyFilesUtil.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/Milvustestv2ApplicationTests.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/AlterAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/CreateAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/DescribeAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/DropAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/ListAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/CreateCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/DescribeCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/DropCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/GetCollectionStatsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/HasCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/ListCollectionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/RenameCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/CreateIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/DescribeIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/DropIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/ListIndexesTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/LoadCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/LoadPartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/ReleaseCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/ReleasePartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/partition/CreatePartitionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/partition/DropPartitionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/partition/HasPartitionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/partition/ListPartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/CreateRoleTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/CreateUserTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/DescribeRoleTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/DescribeUserTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/DropRoleTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/DropUserTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/GrantPrivilegeTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/GrantRoleTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/ListRolesTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/ListUsersTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/RevokePrivilegeTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/RevokeRoleTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/rbac/UpdatePasswordTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/DeleteTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/GetTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/InsertTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/QueryTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/UpsertTest.java
  tests/milvustestv2/src/test/resources/run.properties
  tests/milvustestv2/src/test/resources/testdata/db_admin.json
  tests/milvustestv2/src/test/resources/testdata/privilege.json
  tests/milvustestv2/testng.xml
Labels: size/XXL

#777 search interface supprt not specify metricType
  src/main/java/io/milvus/param/MetricType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/QueryNodeSingleSearch.java
  src/main/java/io/milvus/param/dml/SearchParam.java
  src/main/java/io/milvus/response/DescIndexResponseWrapper.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed
