Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-01, with the labels that each got.

#730 Prepare for v2.2.16
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#731 Fix typo
  README.md
Labels: lgtm, approved, ci-passed, size/XS

#735 replace grpc-netty to grpc-netty-shared
  pom.xml
  src/main/java/io/milvus/client/MilvusServiceClient.java
Labels: lgtm, approved, ci-passed, size/S

#736 replace grpc-netty to grpc-netty-shared
  pom.xml
  src/main/java/io/milvus/client/MilvusServiceClient.java
Labels: lgtm, approved, ci-passed, size/S

#740 support indexType not specify
  src/main/java/io/milvus/param/IndexType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
Labels: lgtm, approved, ci-passed, size/S

#741 Support without specifying metricType and indexType
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/IndexType.java
  src/main/java/io/milvus/param/MetricType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
  src/main/java/io/milvus/response/DescIndexResponseWrapper.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#742 Support without specifying metricType and indexType
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/param/IndexType.java
  src/main/java/io/milvus/param/MetricType.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/index/CreateIndexParam.java
  src/main/java/io/milvus/response/DescIndexResponseWrapper.java
  src/test/java/io/milvus/client/MilvusServiceClientTest.java
Labels: size/L, lgtm, approved, ci-passed

#748 Update java api parameters with python to keep in sync
  src/main/java/io/milvus/v2/client/ConnectConfig.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/examples/Simple.java
  src/main/java/io/milvus/v2/examples/Simple_Schema.java
  src/main/java/io/milvus/v2/exception/ErrorCode.java
  src/main/java/io/milvus/v2/exception/MilvusClientException.java
  src/main/java/io/milvus/v2/service/BaseService.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionWithSchemaReq.java
  src/main/java/io/milvus/v2/service/collection/request/GetLoadStateReq.java
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/index/request/CreateIndexReq.java
  src/main/java/io/milvus/v2/service/partition/PartitionService.java
  src/main/java/io/milvus/v2/service/rbac/RoleService.java
  src/main/java/io/milvus/v2/service/rbac/UserService.java
  src/main/java/io/milvus/v2/service/utility/UtilityService.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/request/GetReq.java
  src/main/java/io/milvus/v2/service/vector/request/InsertReq.java
  src/main/java/io/milvus/v2/service/vector/request/QueryReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  src/main/java/io/milvus/v2/service/vector/request/UpsertReq.java
  src/main/java/io/milvus/v2/service/vector/response/DeleteResp.java
  src/main/java/io/milvus/v2/service/vector/response/InsertResp.java
  src/main/java/io/milvus/v2/service/vector/response/UpsertResp.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/main/java/io/milvus/v2/utils/DataUtils.java
  src/main/java/io/milvus/v2/utils/RpcUtils.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
  src/test/java/io/milvus/v2/BaseTest.java
  src/test/java/io/milvus/v2/service/collection/CollectionTest.java
  src/test/java/io/milvus/v2/service/index/IndexTest.java
  src/test/java/io/milvus/v2/service/partition/PartitionTest.java
  src/test/java/io/milvus/v2/service/rbac/RoleTest.java
  src/test/java/io/milvus/v2/service/rbac/UserTest.java
  src/test/java/io/milvus/v2/service/utility/UtilityTest.java
  src/test/java/io/milvus/v2/service/vector/VectorTest.java
Labels: size/XXL, ci-passed
