Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-06, with the labels that each got.

#915 Verify retrieve
  examples/main/java/io/milvus/v1/CommonUtils.java
  examples/main/java/io/milvus/v1/Float16VectorExample.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#914 Verify retrieve
  examples/main/java/io/milvus/v1/CommonUtils.java
  examples/main/java/io/milvus/v1/Float16VectorExample.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#918 Group by for V2
  src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#921 Group by for V2 (#918)
  src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#922 enhance: enable AlterDatabase and DescribeDatabase API
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/collection/AlterDatabaseParam.java
  src/main/java/io/milvus/param/collection/DescribeDatabaseParam.java
  src/main/java/io/milvus/response/DescDBResponseWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#923 enhance: enable AlterDatabase and DescribeDatabase API
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/client/MilvusMultiServiceClient.java
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/param/Constant.java
  src/main/java/io/milvus/param/collection/AlterDatabaseParam.java
  src/main/java/io/milvus/param/collection/DescribeDatabaseParam.java
  src/main/java/io/milvus/response/DescDBResponseWrapper.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#924 Cache collection schema for insert/upsert
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#925 Cache collection schema for insert/upsert
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#928 Fix a bug of describeCollection V2
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#929 Fix a bug of describeCollection V2
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#937 Exclude the slf4j-reload4j dependency from hadoop-client
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#938 [cherry-pick] Exclude the slf4j-reload4j dependency from hadoop-client
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#939 [cherry-pick] Exclude the slf4j-reload4j dependency from hadoop-client
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#936 Improve usability of float16
  docker-compose.yml
  examples/main/java/io/milvus/v1/CommonUtils.java
  examples/main/java/io/milvus/v1/Float16VectorExample.java
  examples/main/java/io/milvus/v1/GeneralExample.java
  examples/main/java/io/milvus/v1/SparseVectorExample.java
  examples/main/java/io/milvus/v2/Float16VectorExample.java
  src/main/java/io/milvus/bulkwriter/common/utils/GeneratorUtils.java
  src/main/java/io/milvus/common/utils/Float16Utils.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/main/java/io/milvus/v2/service/vector/request/data/BFloat16Vec.java
  src/main/java/io/milvus/v2/service/vector/request/data/Float16Vec.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#940 Improve usability of float16
  docker-compose.yml
  examples/main/java/io/milvus/v1/CommonUtils.java
  examples/main/java/io/milvus/v1/Float16VectorExample.java
  examples/main/java/io/milvus/v1/GeneralExample.java
  examples/main/java/io/milvus/v1/SparseVectorExample.java
  examples/main/java/io/milvus/v2/Float16VectorExample.java
  src/main/java/io/milvus/bulkwriter/common/utils/GeneratorUtils.java
  src/main/java/io/milvus/common/utils/Float16Utils.java
  src/main/java/io/milvus/param/ParamUtils.java
  src/main/java/io/milvus/param/collection/FieldType.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/main/java/io/milvus/v2/service/vector/request/data/BFloat16Vec.java
  src/main/java/io/milvus/v2/service/vector/request/data/Float16Vec.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#941 Fix a bug of max_capacity range
  src/main/java/io/milvus/param/collection/FieldType.java
Labels: lgtm, approved, ci-passed, size/XS

#942 Iterator for V2
  .gitignore
  examples/main/java/io/milvus/v1/BinaryVectorExample.java
  examples/main/java/io/milvus/v1/Float16VectorExample.java
  examples/main/java/io/milvus/v1/IteratorExample.java
  examples/main/java/io/milvus/v1/SparseVectorExample.java
  examples/main/java/io/milvus/v2/Float16VectorExample.java
  examples/main/java/io/milvus/v2/IteratorExample.java
  examples/main/java/io/milvus/v2/SimpleExample.java
  src/main/java/io/milvus/common/utils/Float16Utils.java
  src/main/java/io/milvus/orm/iterator/IteratorAdapterV2.java
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/QueryResultsWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/main/java/io/milvus/response/basic/RowRecordWrapper.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/request/QueryIteratorReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchIteratorReq.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#945 Iterator for V2
  .gitignore
  examples/main/java/io/milvus/v1/BinaryVectorExample.java
  examples/main/java/io/milvus/v1/Float16VectorExample.java
  examples/main/java/io/milvus/v1/IteratorExample.java
  examples/main/java/io/milvus/v1/SparseVectorExample.java
  examples/main/java/io/milvus/v2/Float16VectorExample.java
  examples/main/java/io/milvus/v2/IteratorExample.java
  examples/main/java/io/milvus/v2/SimpleExample.java
  src/main/java/io/milvus/common/utils/Float16Utils.java
  src/main/java/io/milvus/orm/iterator/IteratorAdapterV2.java
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/QueryResultsWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/main/java/io/milvus/response/basic/RowRecordWrapper.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/request/QueryIteratorReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchIteratorReq.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#946 Rename distance to score
  examples/main/java/io/milvus/v1/BinaryVectorExample.java
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  examples/main/java/io/milvus/v1/Float16VectorExample.java
  examples/main/java/io/milvus/v1/GeneralExample.java
  examples/main/java/io/milvus/v1/HighLevelExample.java
  examples/main/java/io/milvus/v1/HybridSearchExample.java
  examples/main/java/io/milvus/v1/IteratorExample.java
  examples/main/java/io/milvus/v1/SimpleExample.java
  examples/main/java/io/milvus/v1/SparseVectorExample.java
  examples/main/java/io/milvus/v2/Float16VectorExample.java
  examples/main/java/io/milvus/v2/IteratorExample.java
  examples/main/java/io/milvus/v2/SimpleExample.java
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#947 Rename distance to score
  examples/main/java/io/milvus/v1/BinaryVectorExample.java
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  examples/main/java/io/milvus/v1/Float16VectorExample.java
  examples/main/java/io/milvus/v1/GeneralExample.java
  examples/main/java/io/milvus/v1/HighLevelExample.java
  examples/main/java/io/milvus/v1/HybridSearchExample.java
  examples/main/java/io/milvus/v1/IteratorExample.java
  examples/main/java/io/milvus/v1/SimpleExample.java
  examples/main/java/io/milvus/v1/SparseVectorExample.java
  examples/main/java/io/milvus/v2/Float16VectorExample.java
  examples/main/java/io/milvus/v2/IteratorExample.java
  examples/main/java/io/milvus/v2/SimpleExample.java
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#948 Rename distance to score
  .gitignore
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
Labels: lgtm, approved, ci-passed, size/S

#950 Fix a typo
  src/main/java/io/milvus/response/SearchResultsWrapper.java
Labels: lgtm, approved, ci-passed, size/XS

#951 Fix a typo
  src/main/java/io/milvus/response/SearchResultsWrapper.java
Labels: lgtm, approved, ci-passed, size/XS

#949 Iterator for V2
  examples/main/java/io/milvus/v1/BinaryVectorExample.java
  examples/main/java/io/milvus/v1/BulkWriterExample.java
  examples/main/java/io/milvus/v1/CommonUtils.java
  examples/main/java/io/milvus/v1/GeneralExample.java
  examples/main/java/io/milvus/v1/HighLevelExample.java
  examples/main/java/io/milvus/v1/IteratorExample.java
  examples/main/java/io/milvus/v1/RBACExample.java
  examples/main/java/io/milvus/v1/SimpleExample.java
  examples/main/java/io/milvus/v1/TLSExample.java
  examples/main/java/io/milvus/v2/IteratorExample.java
  examples/main/java/io/milvus/v2/SimpleExample.java
  examples/main/resources/tls/gen.sh
  examples/main/resources/tls/openssl.cnf
  src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  src/main/java/io/milvus/orm/iterator/IteratorAdapterV2.java
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
  src/main/java/io/milvus/response/FieldDataWrapper.java
  src/main/java/io/milvus/response/QueryResultsWrapper.java
  src/main/java/io/milvus/response/SearchResultsWrapper.java
  src/main/java/io/milvus/response/basic/RowRecordWrapper.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/examples/Simple.java
  src/main/java/io/milvus/v2/examples/Simple_Schema.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  src/main/java/io/milvus/v2/service/index/response/DescribeIndexResp.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/service/vector/request/QueryIteratorReq.java
  src/main/java/io/milvus/v2/service/vector/request/SearchIteratorReq.java
  src/main/java/io/milvus/v2/service/vector/request/data/BinaryVec.java
  src/main/java/io/milvus/v2/service/vector/request/data/FloatVec.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/main/java/io/milvus/v2/utils/SchemaUtils.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#954 Refine code
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
Labels: lgtm, approved, ci-passed, size/M

#952 AlterCollection/AlterIndex for V2
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/AlterCollectionReq.java
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/index/request/AlterIndexReq.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#953 AlterCollection/AlterIndex for V2
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/request/AlterCollectionReq.java
  src/main/java/io/milvus/v2/service/index/IndexService.java
  src/main/java/io/milvus/v2/service/index/request/AlterIndexReq.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed
