Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-05, with the labels that each got.

#884 Fix the error of cast float to double precision in searchIterator.
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
Labels: lgtm, approved, ci-passed, size/S

#885 [cherry-pick] Fix the error of cast float to double precision in searchIterator
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
Labels: lgtm, approved, ci-passed, size/S

#886 [cherry-pick] Fix the error of cast float to double precision in searchIterator
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
Labels: lgtm, approved, ci-passed, size/S

#883 MetricType was not initialized in SearchIterator#executeNextSearch (#881), and cast errors occured in SearchIterator#checkRmRangeSearchParameters (#887)
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
Labels: lgtm, approved, ci-passed, size/XS

#888 Bugfix: MetricType was not initialized in SeachIterator#executeNextSearch (#881)
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
Labels: lgtm, approved, ci-passed, size/XS

#889 Bugfix: MetricType was not initialized in SeachIterator#executeNextSearch(#881)
  src/main/java/io/milvus/orm/iterator/SearchIterator.java
Labels: lgtm, approved, ci-passed, size/XS

#894 support zilliz cloud elastic serverless.
  src/main/java/io/milvus/common/constant/MilvusClientConstant.java
  src/main/java/io/milvus/param/ConnectParam.java
Labels: lgtm, approved, ci-passed, size/XS

#895 support zilliz cloud elastic serverless.
  src/main/java/io/milvus/common/constant/MilvusClientConstant.java
  src/main/java/io/milvus/param/ConnectParam.java
Labels: lgtm, approved, ci-passed, size/XS

#896 support zilliz cloud elastic serverless.
  src/main/java/io/milvus/common/constant/MilvusClientConstant.java
  src/main/java/io/milvus/param/ConnectParam.java
Labels: lgtm, approved, ci-passed, size/XS

#891 fix queryIterator error if varchar primary
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
Labels: lgtm, approved, ci-passed, size/XS

#892 [cherry-pick]fix queryIterator error if varchar primary
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
Labels: lgtm, approved, ci-passed, size/XS

#893 [cherry-pick]fix queryIterator error if varchar primary
  src/main/java/io/milvus/orm/iterator/QueryIterator.java
Labels: lgtm, approved, ci-passed, size/XS

#897 Prepare for v2.4.1
  CHANGELOG.md
  README.md
  docker-compose.yml
  examples/pom.xml
  pom.xml
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#898 Prepare for v2.3.7
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#905 Add BinaryVector example
  examples/main/java/io/milvus/BinaryVectorExample.java
Labels: size/L, lgtm, approved, ci-passed
