Repository milvus-io/milvus-sdk-java, pull requests merged in 2024-08, with the labels that each got.

#1010 ListIndexes returns empty if no index exists
  src/main/java/io/milvus/v2/service/index/IndexService.java
Labels: lgtm, approved, ci-passed, size/XS

#1011 ListIndexes returns empty if no index exists
  src/main/java/io/milvus/v2/service/index/IndexService.java
Labels: lgtm, approved, ci-passed, size/XS

#1012 ListIndexes returns empty if no index exists
  src/main/java/io/milvus/v2/service/index/IndexService.java
Labels: lgtm, approved, ci-passed, size/XS

#1017 Get server version interface
  .github/workflows/java_sdk_ci_test.yaml
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1018 Get server version interface
  .github/workflows/java_sdk_ci_test.yaml
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1019 Get server version interface
  .github/workflows/java_sdk_ci_test.yaml
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
  src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1020 Client pool for V1 V2
  pom.xml
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/pool/ClientPool.java
  src/main/java/io/milvus/pool/MilvusClientV1Pool.java
  src/main/java/io/milvus/pool/MilvusClientV2Pool.java
  src/main/java/io/milvus/pool/PoolClientFactory.java
  src/main/java/io/milvus/pool/PoolConfig.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1021 Client pool for V1 V2
  pom.xml
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/pool/ClientPool.java
  src/main/java/io/milvus/pool/MilvusClientV1Pool.java
  src/main/java/io/milvus/pool/MilvusClientV2Pool.java
  src/main/java/io/milvus/pool/PoolClientFactory.java
  src/main/java/io/milvus/pool/PoolConfig.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1016 Client pool for V1 V2
  pom.xml
  src/main/java/io/milvus/client/MilvusServiceClient.java
  src/main/java/io/milvus/pool/ClientPool.java
  src/main/java/io/milvus/pool/MilvusClientV1Pool.java
  src/main/java/io/milvus/pool/MilvusClientV2Pool.java
  src/main/java/io/milvus/pool/PoolClientFactory.java
  src/main/java/io/milvus/pool/PoolConfig.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1022 Fix thread-safe insert/upsert bug of V2
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/utils/DataUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1023 Fix thread-safe insert/upsert bug of V2
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/utils/DataUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1024 Fix thread-safe insert/upsert bug of V2
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/utils/DataUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1025 Example for client pool
  examples/main/java/io/milvus/v1/ClientPoolExample.java
  examples/main/java/io/milvus/v2/ClientPoolExample.java
  src/main/java/io/milvus/pool/ClientPool.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1026 Example for client pool
  examples/main/java/io/milvus/v1/ClientPoolExample.java
  examples/main/java/io/milvus/v2/ClientPoolExample.java
  src/main/java/io/milvus/pool/ClientPool.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1027 Example for client pool
  examples/main/java/io/milvus/v1/ClientPoolExample.java
  examples/main/java/io/milvus/v2/ClientPoolExample.java
  src/main/java/io/milvus/pool/ClientPool.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1028 Fix bug of describeCollection V2
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/pool/ClientPool.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1029 Fix bug of describeCollection V2
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/pool/ClientPool.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1030 Fix bug of describeCollection V2
  src/main/java/io/milvus/client/MilvusClient.java
  src/main/java/io/milvus/pool/ClientPool.java
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/service/collection/CollectionService.java
  src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  src/main/java/io/milvus/v2/service/vector/VectorService.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
  src/main/java/io/milvus/v2/utils/ConvertUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1033 Prepare for v2.3.9
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1037 modify generate bf16 and f16 vector.
  .github/workflows/java_sdk_ci_test.yaml
  tests/milvustestv2/pom.xml
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/BaseTest.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonData.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/utils/Float16Utils.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/CreateAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/CreateCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/GetCollectionStatsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/database/AlterDatabaseTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/database/CreateDatabaseTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/database/DescribeDatabaseTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/database/DropDatabaseTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/CreateIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/DescribeIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/DropIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/ListIndexesTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/LoadCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/LoadPartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/ReleaseCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/ReleasePartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/DeleteTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/GetTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/InsertTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/UpsertTest.java
  tests/milvustestv2/src/test/java/resources/cluster-values.yaml
  tests/milvustestv2/src/test/java/resources/docker-compose.yml
  tests/milvustestv2/src/test/java/resources/scripts/docker_image_find_tag.sh
  tests/milvustestv2/src/test/java/resources/scripts/install_milvus.sh
  tests/milvustestv2/src/test/java/resources/scripts/install_milvus_cluster.sh
  tests/milvustestv2/src/test/java/resources/scripts/install_milvus_standalone.sh
  tests/milvustestv2/src/test/java/resources/scripts/modify_config.sh
  tests/milvustestv2/src/test/java/resources/scripts/uninstall_milvus.sh
  tests/milvustestv2/src/test/java/resources/standalone-values.yaml
  tests/milvustestv2/src/test/resources/run.properties
Labels: lgtm, size/XXL, approved, ci-passed

#1039 modify generate bf16 and f16 vector.
  .github/workflows/java_sdk_ci_test.yaml
  tests/milvustestv2/pom.xml
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/BaseTest.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonData.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/params/FieldParam.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/utils/Float16Utils.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/CreateAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/CreateCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/GetCollectionStatsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/database/AlterDatabaseTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/database/CreateDatabaseTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/database/DescribeDatabaseTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/database/DropDatabaseTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/CreateIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/DescribeIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/DropIndexTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/ListIndexesTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/LoadCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/LoadPartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/ReleaseCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/loadRelease/ReleasePartitionsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/DeleteTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/GetTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/InsertTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/UpsertTest.java
  tests/milvustestv2/src/test/java/resources/cluster-values.yaml
  tests/milvustestv2/src/test/java/resources/docker-compose.yml
  tests/milvustestv2/src/test/java/resources/scripts/docker_image_find_tag.sh
  tests/milvustestv2/src/test/java/resources/scripts/install_milvus.sh
  tests/milvustestv2/src/test/java/resources/scripts/install_milvus_cluster.sh
  tests/milvustestv2/src/test/java/resources/scripts/install_milvus_standalone.sh
  tests/milvustestv2/src/test/java/resources/scripts/modify_config.sh
  tests/milvustestv2/src/test/java/resources/scripts/uninstall_milvus.sh
  tests/milvustestv2/src/test/java/resources/standalone-values.yaml
  tests/milvustestv2/src/test/resources/run.properties
Labels: lgtm, size/XXL, approved, ci-passed

#1041 Add examples for V2
  docker-compose.yml
  examples/main/java/io/milvus/v1/JsonFieldExample.java
  examples/main/java/io/milvus/v1/SimpleExample.java
  examples/main/java/io/milvus/v1/TLSExample.java
  examples/main/java/io/milvus/v2/BinaryVectorExample.java
  examples/main/java/io/milvus/v2/ClientPoolExample.java
  examples/main/java/io/milvus/v2/Float16VectorExample.java
  examples/main/java/io/milvus/v2/HybridSearchExample.java
  examples/main/java/io/milvus/v2/IteratorExample.java
  examples/main/java/io/milvus/v2/JsonFieldExample.java
  examples/main/java/io/milvus/v2/SimpleExample.java
  examples/main/java/io/milvus/v2/SparseVectorExample.java
  examples/main/java/io/milvus/v2/TLSExample.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#1042 Add examples for V2
  docker-compose.yml
  examples/main/java/io/milvus/v1/JsonFieldExample.java
  examples/main/java/io/milvus/v1/SimpleExample.java
  examples/main/java/io/milvus/v1/TLSExample.java
  examples/main/java/io/milvus/v2/BinaryVectorExample.java
  examples/main/java/io/milvus/v2/ClientPoolExample.java
  examples/main/java/io/milvus/v2/Float16VectorExample.java
  examples/main/java/io/milvus/v2/HybridSearchExample.java
  examples/main/java/io/milvus/v2/IteratorExample.java
  examples/main/java/io/milvus/v2/JsonFieldExample.java
  examples/main/java/io/milvus/v2/SimpleExample.java
  examples/main/java/io/milvus/v2/SparseVectorExample.java
  examples/main/java/io/milvus/v2/TLSExample.java
  src/test/java/io/milvus/client/MilvusClientDockerTest.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#1043 add testcases abort enable mmap
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/DescribeCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/AlterIndexTest.java
Labels: lgtm, approved, ci-passed, size/M

#1044 add testcases abort enable mmap (#1043)
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/DescribeCollectionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/AlterIndexTest.java
Labels: lgtm, approved, ci-passed, size/M

#1045 fix: add description for field schema
  src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: size/XS

#1046 add fluent api for AlterCollectionReq & CreateCollectionReq
  .gitignore
  README.md
  src/main/java/io/milvus/v2/service/collection/request/AlterCollectionReq.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
  src/test/java/io/milvus/v2/service/collection/CollectionTest.java
Labels: lgtm, approved, ci-passed, size/M

#1048 Modify DEVELOPMENT.md
  DEVELOPMENT.md
  README.md
Labels: lgtm, approved, ci-passed, size/S

#1049 [cherry-pick] add fluent api for AlterCollectionReq & CreateCollectionReq (#1046)
  .gitignore
  README.md
  src/main/java/io/milvus/v2/service/collection/request/AlterCollectionReq.java
  src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
  src/test/java/io/milvus/v2/service/collection/CollectionTest.java
Labels: lgtm, approved, ci-passed, size/M

#1050 [cherry-pick] Modify DEVELOPMENT.md (#1048)
  DEVELOPMENT.md
  README.md
Labels: lgtm, approved, ci-passed, size/S

#1047 Preconnect
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1052 Preconnect (#1047)
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1051 Preconnect (#1047)
  src/main/java/io/milvus/v2/client/MilvusClientV2.java
  src/main/java/io/milvus/v2/utils/ClientUtils.java
  src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M
