Repository milvus-io/milvus-sdk-java, pull requests merged in 2025-04, with the labels that each got.

#1351 Fix a regression for parsing JSON field values returned by search/query
  examples/src/main/java/io/milvus/v1/BulkWriterExample.java
  examples/src/main/java/io/milvus/v1/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  examples/src/main/java/io/milvus/v2/JsonFieldExample.java
  sdk-core/src/main/java/io/milvus/response/FieldDataWrapper.java
Labels: lgtm, approved, ci-passed, size/M

#1352 Fix a regression for parsing JSON field values returned by search/query
  examples/src/main/java/io/milvus/v1/BulkWriterExample.java
  examples/src/main/java/io/milvus/v1/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  examples/src/main/java/io/milvus/v2/JsonFieldExample.java
  sdk-core/src/main/java/io/milvus/response/FieldDataWrapper.java
Labels: lgtm, approved, ci-passed, size/M

#1350 Adding in Proxy setting for connection to milvus.
  sdk-core/src/main/java/io/milvus/client/MilvusServiceClient.java
  sdk-core/src/main/java/io/milvus/param/ConnectParam.java
  sdk-core/src/main/java/io/milvus/v2/client/ConnectConfig.java
  sdk-core/src/main/java/io/milvus/v2/utils/ClientUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1355 Fix a bug: incorrect outputFields of query/search with milvus v2.5.8
  examples/src/main/java/io/milvus/v1/BulkWriterExample.java
  examples/src/main/java/io/milvus/v1/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  examples/src/main/java/io/milvus/v2/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/TextMatchExample.java
  sdk-core/src/main/java/io/milvus/response/basic/RowRecordWrapper.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1356 Fix a bug: incorrect outputFields of query/search with milvus v2.5.8
  examples/src/main/java/io/milvus/v1/BulkWriterExample.java
  examples/src/main/java/io/milvus/v1/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  examples/src/main/java/io/milvus/v2/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/TextMatchExample.java
  sdk-core/src/main/java/io/milvus/response/basic/RowRecordWrapper.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1358 [cherry-pick] Adding in Proxy setting for connection to milvus. (#1350)
  sdk-core/src/main/java/io/milvus/client/MilvusServiceClient.java
  sdk-core/src/main/java/io/milvus/param/ConnectParam.java
  sdk-core/src/main/java/io/milvus/v2/client/ConnectConfig.java
  sdk-core/src/main/java/io/milvus/v2/utils/ClientUtils.java
Labels: approved, ci-passed, size/M

#1359 Support offset parameter for hybridSearch interface
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/param/dml/HybridSearchParam.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/HybridSearchReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: lgtm, approved, ci-passed, size/S

#1360 Support offset parameter for hybridSearch interface
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/param/dml/HybridSearchParam.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/HybridSearchReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: lgtm, approved, ci-passed, size/S

#1366 Fix a bug of nullable Array type
  docker-compose.yml
  examples/src/main/java/io/milvus/v1/NullAndDefaultExample.java
  examples/src/main/java/io/milvus/v2/NullAndDefaultExample.java
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/response/FieldDataWrapper.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1367 Fix a bug of nullable Array type
  docker-compose.yml
  examples/src/main/java/io/milvus/v1/NullAndDefaultExample.java
  examples/src/main/java/io/milvus/v2/NullAndDefaultExample.java
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/response/FieldDataWrapper.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1368 Prepare for v2.4.11
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1369 Prepare for v2.5.7
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1370 Prepare for v2.5.7
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1373 Add checkHealth/getPersistentSegmentInfo/getQuerySegmentInfo/transferNode interfaces
  .github/workflows/maven.yml
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/ResourceGroupService.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/TransferNodeReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/UtilityService.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/GetPersistentSegmentInfoReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/GetQuerySegmentInfoReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/response/CheckHealthResp.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/response/GetPersistentSegmentInfoResp.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/response/GetQuerySegmentInfoResp.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1372 Add checkHealth/getPersistentSegmentInfo/getQuerySegmentInfo/transferNode interfaces
  .github/workflows/maven.yml
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/ResourceGroupService.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/TransferNodeReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/UtilityService.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/GetPersistentSegmentInfoReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/GetQuerySegmentInfoReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/response/CheckHealthResp.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/response/GetPersistentSegmentInfoResp.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/response/GetQuerySegmentInfoResp.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1374 Fix a typo
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
Labels: lgtm, approved, ci-passed, size/XS

#1375 Fix a typo
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
Labels: lgtm, approved, ci-passed, size/XS

#1376 Prepare for v2.5.8
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1377 Prepare for v2.5.8
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1379 optim index interface support db
  pom.xml
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/main/java/io/milvus/v2/service/index/request/DescribeIndexReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1380 [cherry-pick] optim index interface support db
  pom.xml
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/main/java/io/milvus/v2/service/index/request/DescribeIndexReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: lgtm, approved, ci-passed, size/M
