Repository milvus-io/milvus-sdk-java, pull requests merged in 2025-03, with the labels that each got.

#1312 BulkWriter supports nullable/default_value for parquet/csv/json
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/BulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/LocalBulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/LocalBulkWriterParam.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/RemoteBulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/RemoteBulkWriterParam.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/clientenum/TypeSize.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/utils/ParquetUtils.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/utils/V2AdapterUtils.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/CSVFileWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/JSONFileWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/ParquetFileWriter.java
  sdk-bulkwriter/src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
  sdk-core/src/main/java/io/milvus/response/FieldDataWrapper.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#1313 BulkWriter supports nullable/default_value for parquet/csv/json
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/BulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/LocalBulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/LocalBulkWriterParam.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/RemoteBulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/RemoteBulkWriterParam.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/clientenum/TypeSize.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/utils/ParquetUtils.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/utils/V2AdapterUtils.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/CSVFileWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/JSONFileWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/ParquetFileWriter.java
  sdk-bulkwriter/src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
  sdk-core/src/main/java/io/milvus/response/FieldDataWrapper.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#1315 Fix a typo
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/LoadCollectionReq.java
Labels: lgtm, approved, ci-passed, size/S

#1316 Fix a typo
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/LoadCollectionReq.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1317 Support describeReplicas() interface
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/ReplicaInfo.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/ShardReplica.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/DescribeReplicasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/response/DescribeReplicasResp.java
  sdk-core/src/main/java/io/milvus/v2/utils/ConvertUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1318 Support describeReplicas() interface
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/ReplicaInfo.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/ShardReplica.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/DescribeReplicasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/response/DescribeReplicasResp.java
  sdk-core/src/main/java/io/milvus/v2/utils/ConvertUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1321 Prepare for v2.5.5
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1322 Prepare for v2.5.5
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1323 optim clientV2 search/query to support db
  sdk-core/src/main/java/io/milvus/v2/common/ConsistencyLevel.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/QueryReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: lgtm, approved, ci-passed, size/S

#1324 [cherry-pick] optim clientV2 search/query to support db
  sdk-core/src/main/java/io/milvus/v2/common/ConsistencyLevel.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/QueryReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/VectorUtils.java
Labels: lgtm, approved, ci-passed, size/S

#1327 SearchIteratorV2
  examples/src/main/java/io/milvus/v2/IteratorExample.java
  sdk-core/src/main/java/io/milvus/orm/iterator/IteratorAdapterV2.java
  sdk-core/src/main/java/io/milvus/orm/iterator/IteratorCache.java
  sdk-core/src/main/java/io/milvus/orm/iterator/SearchIterator.java
  sdk-core/src/main/java/io/milvus/orm/iterator/SearchIteratorV2.java
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/SearchIteratorReqV2.java
  sdk-core/src/main/java/io/milvus/v2/utils/VectorUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1328 SearchIteratorV2
  examples/src/main/java/io/milvus/v2/IteratorExample.java
  sdk-core/src/main/java/io/milvus/orm/iterator/IteratorAdapterV2.java
  sdk-core/src/main/java/io/milvus/orm/iterator/IteratorCache.java
  sdk-core/src/main/java/io/milvus/orm/iterator/SearchIterator.java
  sdk-core/src/main/java/io/milvus/orm/iterator/SearchIteratorV2.java
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/SearchIteratorReqV2.java
  sdk-core/src/main/java/io/milvus/v2/utils/VectorUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1329 External function example for SearchIteratorV2
  examples/src/main/java/io/milvus/v2/IteratorExample.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1330 External function example for SearchIteratorV2
  examples/src/main/java/io/milvus/v2/IteratorExample.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1331 Add sync parameter for loadCollection/loadPartitions/createIndex
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/DropCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/LoadCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/RefreshLoadReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/ReleaseCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/main/java/io/milvus/v2/service/index/request/CreateIndexReq.java
  sdk-core/src/main/java/io/milvus/v2/service/index/request/DescribeIndexReq.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/PartitionService.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/request/LoadPartitionsReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/QueryResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  sdk-core/src/test/java/io/milvus/v2/BaseTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1332 Add sync parameter for loadCollection/loadPartitions/createIndex
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/DropCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/LoadCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/RefreshLoadReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/ReleaseCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/main/java/io/milvus/v2/service/index/request/CreateIndexReq.java
  sdk-core/src/main/java/io/milvus/v2/service/index/request/DescribeIndexReq.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/PartitionService.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/request/LoadPartitionsReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/QueryResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  sdk-core/src/test/java/io/milvus/v2/BaseTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1333 add testcases for random sampling
  .github/workflows/java_sdk_ci_test.yaml
  tests/milvustestv2/pom.xml
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/BaseTest.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/AlterAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/CreateAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/QueryTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/UpsertTest.java
  tests/milvustestv2/src/test/resources/run.properties
Labels: size/L, lgtm, approved, ci-passed

#1334 add testcases for random sampling (#1333)
  .github/workflows/java_sdk_ci_test.yaml
  tests/milvustestv2/pom.xml
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/BaseTest.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/AlterAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/CreateAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/QueryTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/UpsertTest.java
  tests/milvustestv2/src/test/resources/run.properties
Labels: size/L, lgtm, approved, ci-passed

#1336 Fix the issue with dbName in queryV2
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/DescribeCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
Labels: lgtm, approved, ci-passed, size/S

#1337 [cherry-pick] Fix the issue with dbName in queryV2
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/DescribeCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
Labels: lgtm, approved, ci-passed, size/S

#1338 add testcase for json path index
  tests/milvustestv2/pom.xml
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonData.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/bulk/BulkImportTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/database/CreateDatabaseTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/CreateIndexTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1339 add testcase for json path index (#1338)
  tests/milvustestv2/pom.xml
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonData.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/bulk/BulkImportTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/database/CreateDatabaseTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/index/CreateIndexTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1340 Prepare for v2.5.6
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1341 Prepare for v2.5.6
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1346 [cherry-pick] set default options if call Cloud
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/BaseBulkImport.java
Labels: lgtm, approved, ci-passed, size/S

#1345 set default options if call Cloud
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/BaseBulkImport.java
Labels: lgtm, approved, ci-passed, size/S
