Repository milvus-io/milvus-sdk-java, pull requests merged in 2025-05, with the labels that each got.

#1378 Fix a bug that index property was not correctly passed
  sdk-core/src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  sdk-core/src/main/java/io/milvus/response/DescIndexResponseWrapper.java
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/main/java/io/milvus/v2/service/index/response/DescribeIndexResp.java
  sdk-core/src/main/java/io/milvus/v2/utils/ConvertUtils.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/client/MilvusServiceClientTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1383 Fix a bug that index property was not correctly passed
  sdk-core/src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  sdk-core/src/main/java/io/milvus/response/DescIndexResponseWrapper.java
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/main/java/io/milvus/v2/service/index/response/DescribeIndexResp.java
  sdk-core/src/main/java/io/milvus/v2/utils/ConvertUtils.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/client/MilvusServiceClientTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1385 Bump com.google.protobuf:protobuf-java from 3.24.0 to 3.25.5 (#1073)
  pom.xml
  tests/milvustestv2/pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#1386 Update protoc from 3.24.0 to 3.25.5
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#1387 Update protoc from 3.24.0 to 3.25.5
  pom.xml
Labels: lgtm, approved, ci-passed, size/XS

#1388 describeCollection returns collection createUtcTime
  sdk-core/src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  sdk-core/src/main/java/io/milvus/v2/utils/ConvertUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#1389 describeCollection returns collection createUtcTime
  sdk-core/src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  sdk-core/src/main/java/io/milvus/v2/utils/ConvertUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#1390 Avoid an exception of LocalBulkWriter in Java 24 env
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/utils/ParquetReaderUtils.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/utils/ParquetUtils.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/ParquetFileWriter.java
Labels: lgtm, approved, ci-passed, size/S

#1391 Avoid an exception of LocalBulkWriter in Java 24 env
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/utils/ParquetReaderUtils.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/utils/ParquetUtils.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/ParquetFileWriter.java
Labels: lgtm, approved, ci-passed, size/S

#1394 Support runAnalyzer() interface
  docker-compose.yml
  pom.xml
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/RunAnalyzerReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/RunAnalyzerResp.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1395 Support runAnalyzer() interface
  docker-compose.yml
  pom.xml
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/RunAnalyzerReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/RunAnalyzerResp.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1397 Make CreateSchema() to be static
  docker-compose.yml
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/utils/ConvertUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
  tests/milvustest/pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1398 Make CreateSchema() to be static
  docker-compose.yml
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/utils/ConvertUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
  tests/milvustest/pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1400 Prepare for v2.5.9
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1401 Prepare for v2.5.9
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M

#1403 Support multi-language analyzer
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#1404 Support multi-language analyzer
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#1406 Refine code
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  sdk-core/src/main/java/io/milvus/v2/service/database/response/ListDatabasesResp.java
  sdk-core/src/main/java/io/milvus/v2/service/index/response/DescribeIndexResp.java
  sdk-core/src/main/java/io/milvus/v2/service/rbac/response/DescribeRoleResp.java
  sdk-core/src/main/java/io/milvus/v2/service/rbac/response/DescribeUserResp.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/TransferNodeReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/InsertResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/QueryResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/RunAnalyzerResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1407 Refine code
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/response/DescribeCollectionResp.java
  sdk-core/src/main/java/io/milvus/v2/service/database/response/ListDatabasesResp.java
  sdk-core/src/main/java/io/milvus/v2/service/index/response/DescribeIndexResp.java
  sdk-core/src/main/java/io/milvus/v2/service/rbac/response/DescribeRoleResp.java
  sdk-core/src/main/java/io/milvus/v2/service/rbac/response/DescribeUserResp.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/TransferNodeReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/InsertResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/QueryResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/RunAnalyzerResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1409 Refine code
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/response/FieldDataWrapper.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  sdk-core/src/test/java/io/milvus/TestUtils.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M

#1410 add deal if convert typeParams error
  sdk-core/src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1411 [cherry-pick] optim schema convert error
  sdk-core/src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1415 Fix a bug of listIndexes()
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1416 Fix a bug of listIndexes()
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1417 Add function type for 2.6
  sdk-core/src/main/java/io/milvus/common/clientenum/FunctionType.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: lgtm, approved, ci-passed, size/S

#1419 Reformat SearchResult/IDScore print content to show primary key
  examples/src/main/java/io/milvus/v1/BinaryVectorExample.java
  examples/src/main/java/io/milvus/v1/CommonUtils.java
  examples/src/main/java/io/milvus/v1/Float16VectorExample.java
  examples/src/main/java/io/milvus/v1/GeneralExample.java
  examples/src/main/java/io/milvus/v1/SparseVectorExample.java
  examples/src/main/java/io/milvus/v2/BinaryVectorExample.java
  examples/src/main/java/io/milvus/v2/Float16VectorExample.java
  examples/src/main/java/io/milvus/v2/FullTextSearchExample.java
  examples/src/main/java/io/milvus/v2/GeneralExample.java
  examples/src/main/java/io/milvus/v2/HybridSearchExample.java
  examples/src/main/java/io/milvus/v2/SparseVectorExample.java
  examples/src/main/java/io/milvus/v2/TextMatchExample.java
  sdk-core/src/main/java/io/milvus/response/SearchResultsWrapper.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  sdk-core/src/main/java/io/milvus/v2/utils/ConvertUtils.java
Labels: size/L, lgtm, approved, ci-passed

#1420 Reformat SearchResult/IDScore print content to show primary key
  examples/src/main/java/io/milvus/v1/BinaryVectorExample.java
  examples/src/main/java/io/milvus/v1/CommonUtils.java
  examples/src/main/java/io/milvus/v1/Float16VectorExample.java
  examples/src/main/java/io/milvus/v1/GeneralExample.java
  examples/src/main/java/io/milvus/v1/SparseVectorExample.java
  examples/src/main/java/io/milvus/v2/BinaryVectorExample.java
  examples/src/main/java/io/milvus/v2/Float16VectorExample.java
  examples/src/main/java/io/milvus/v2/FullTextSearchExample.java
  examples/src/main/java/io/milvus/v2/GeneralExample.java
  examples/src/main/java/io/milvus/v2/HybridSearchExample.java
  examples/src/main/java/io/milvus/v2/Int8VectorExample.java
  examples/src/main/java/io/milvus/v2/SparseVectorExample.java
  examples/src/main/java/io/milvus/v2/TextMatchExample.java
  sdk-core/src/main/java/io/milvus/response/SearchResultsWrapper.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/SearchResp.java
  sdk-core/src/main/java/io/milvus/v2/utils/ConvertUtils.java
Labels: size/L, lgtm, approved, ci-passed
