Repository milvus-io/milvus-sdk-java, pull requests merged in 2025-09, with the labels that each got.

#1579 Fix a bug of QueryIterator that offset cannot exceed 16384
  sdk-core/src/main/java/io/milvus/orm/iterator/QueryIterator.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M, dco-passed

#1583 Fix a bug of QueryIterator that offset cannot exceed 16384
  sdk-core/src/main/java/io/milvus/orm/iterator/QueryIterator.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M, dco-passed

#1587 Support FunctionScore, multi-reranker for search/hybridSearch
  examples/src/main/java/io/milvus/v2/HybridSearchExample.java
  sdk-core/src/main/java/io/milvus/orm/iterator/QueryIterator.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/FunctionScore.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/HybridSearchReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/VectorUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed, dco-passed

#1588 Support FunctionScore, multi-reranker for search/hybridSearch
  examples/src/main/java/io/milvus/v2/HybridSearchExample.java
  sdk-core/src/main/java/io/milvus/orm/iterator/QueryIterator.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/FunctionScore.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/HybridSearchReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/SearchReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/VectorUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed, dco-passed

#1595 ClientPool supports different ConnectConfig for different key
  docker-compose.yml
  examples/src/main/java/io/milvus/v1/ClientPoolExample.java
  examples/src/main/java/io/milvus/v2/ClientPoolExample.java
  sdk-core/src/main/java/io/milvus/pool/ClientPool.java
  sdk-core/src/main/java/io/milvus/pool/PoolClientFactory.java
  sdk-core/src/main/java/io/milvus/pool/PoolConfig.java
  sdk-core/src/test/java/io/milvus/TestUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#1596 Add some util methods for ClientPool
  sdk-core/src/main/java/io/milvus/pool/ClientPool.java
  sdk-core/src/main/java/io/milvus/pool/PoolClientFactory.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M, dco-passed

#1602 Prepare for v2.5.13
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/S, dco-passed

#1599 Prepare for v2.6.4
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M, dco-passed

#1603 Set ClientPool maxTotalPerKey default value to 50
  sdk-core/src/main/java/io/milvus/pool/PoolConfig.java
Labels: lgtm, approved, ci-passed, size/XS, dco-passed

#1604 Set ClientPool maxTotalPerKey default value to 50
  sdk-core/src/main/java/io/milvus/pool/PoolConfig.java
Labels: lgtm, approved, ci-passed, size/XS, dco-passed

#1605 Set ClientPool maxTotalPerKey default value to 50
  sdk-core/src/main/java/io/milvus/pool/PoolConfig.java
Labels: lgtm, approved, ci-passed, size/XS, dco-passed

#1607 [cherry-pick] bulk_import add apiKey note
  examples/src/main/java/io/milvus/v1/BulkWriterExample.java
  examples/src/main/java/io/milvus/v2/bulkwriter/BulkWriterRemoteExample.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/describe/BaseDescribeImportRequest.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/BaseImportRequest.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/list/BaseListImportJobsRequest.java
Labels: lgtm, approved, ci-passed, size/S, dco-passed

#1606 bulk_import add apiKey note
  examples/src/main/java/io/milvus/v1/BulkWriterExample.java
  examples/src/main/java/io/milvus/v2/bulkwriter/BulkWriterRemoteExample.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/describe/BaseDescribeImportRequest.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/import_/BaseImportRequest.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/request/list/BaseListImportJobsRequest.java
Labels: lgtm, approved, ci-passed, size/S, dco-passed

#1610 Fix a bug of delete() that databaseName doesnt work
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/utils/DataUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M, dco-passed

#1611 Fix a bug of delete() that databaseName doesnt work
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/utils/DataUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M, dco-passed

#1612 Fix a bug of delete() that databaseName doesnt work
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/utils/DataUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/M, dco-passed

#1622 Add example for struct field
  examples/src/main/java/io/milvus/v2/StructExample.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed, dco-passed

#1621 Add example for struct field
  examples/src/main/java/io/milvus/v2/StructExample.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed, dco-passed

#1626 Support Geometry field
  docker-compose.yml
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/BulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/utils/ParquetUtils.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/ParquetFileWriter.java
  sdk-bulkwriter/src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/response/FieldDataWrapper.java
  sdk-core/src/main/java/io/milvus/v2/common/DataType.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/InsertReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/UpsertReq.java
  sdk-core/src/test/java/io/milvus/TestUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed, dco-passed

#1627 Support Geometry field
  docker-compose.yml
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/BulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/utils/ParquetUtils.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/ParquetFileWriter.java
  sdk-bulkwriter/src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/response/FieldDataWrapper.java
  sdk-core/src/main/java/io/milvus/v2/common/DataType.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/InsertReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/UpsertReq.java
  sdk-core/src/test/java/io/milvus/TestUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed, dco-passed

#1630 Add geometry example
  docker-compose.yml
  examples/src/main/java/io/milvus/v2/GeometryExample.java
  sdk-core/src/main/java/io/milvus/v2/common/IndexParam.java
  sdk-core/src/test/java/io/milvus/TestUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed, dco-passed

#1631 Add geometry example
  docker-compose.yml
  examples/src/main/java/io/milvus/v2/GeometryExample.java
  sdk-core/src/main/java/io/milvus/v2/common/IndexParam.java
  sdk-core/src/test/java/io/milvus/TestUtils.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed, dco-passed

#1632 Prepare for v2.6.5
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M, dco-passed

#1633 Prepare for v2.5.14
  CHANGELOG.md
  README.md
  docker-compose.yml
  examples/pom.xml
  pom.xml
  sdk-core/src/test/java/io/milvus/TestUtils.java
Labels: lgtm, approved, ci-passed, size/M, dco-passed

#1634 Prepare for v2.6.5
  CHANGELOG.md
  README.md
  examples/pom.xml
  pom.xml
Labels: lgtm, approved, ci-passed, size/M, dco-passed
