Repository milvus-io/milvus-sdk-java, pull requests merged in 2025-07, with the labels that each got.

#1441 BulkWriter supports Int8Vector
  README.md
  examples/src/main/java/io/milvus/v1/CommonUtils.java
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/BulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/common/utils/ParquetUtils.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/ParquetFileWriter.java
  sdk-bulkwriter/src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
  sdk-bulkwriter/src/test/java/io/milvus/bulkwriter/TestUtils.java
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
Labels: approved, ci-passed, size/M

#1443 Fix a bug of SearchResultsWrapper.getRowRecords() that returns wrong data for output fields
  examples/src/main/java/io/milvus/v1/CommonUtils.java
  examples/src/main/java/io/milvus/v1/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/JsonFieldExample.java
  sdk-core/src/main/java/io/milvus/response/SearchResultsWrapper.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1445 Fix a bug of SearchResultsWrapper.getRowRecords() that returns wrong data for output fields
  examples/src/main/java/io/milvus/v1/CommonUtils.java
  examples/src/main/java/io/milvus/v1/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/JsonFieldExample.java
  sdk-core/src/main/java/io/milvus/response/SearchResultsWrapper.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1444 Fix a bug of SearchResultsWrapper.getRowRecords() that returns wrong data for output fields
  examples/src/main/java/io/milvus/v1/CommonUtils.java
  examples/src/main/java/io/milvus/v1/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/JsonFieldExample.java
  sdk-core/src/main/java/io/milvus/response/SearchResultsWrapper.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1447 Fix a bug of collection schema cache for V1 and V2
  docker-compose.yml
  sdk-core/src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/test/java/io/milvus/TestUtils.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1448 Fix a bug of collection schema cache for V1 and V2
  sdk-core/src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1449 Fix a bug of collection schema cache for V1 and V2
  docker-compose.yml
  sdk-core/src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/test/java/io/milvus/TestUtils.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1451 Refine the schema cache machinery and add test cases
  sdk-core/src/main/java/io/milvus/client/AbstractMilvusGrpcClient.java
  sdk-core/src/main/java/io/milvus/client/MilvusServiceClient.java
  sdk-core/src/main/java/io/milvus/common/utils/GTsDict.java
  sdk-core/src/main/java/io/milvus/v2/client/ConnectConfig.java
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/BaseService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/DropCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/DeleteReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/InsertReq.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/request/UpsertReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/DataUtils.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/XL

#1459 Avoid exception when search result is empty
  sdk-core/src/main/java/io/milvus/response/SearchResultsWrapper.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/client/MilvusServiceClientTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1460 Avoid exception when search result is empty
  sdk-core/src/main/java/io/milvus/response/SearchResultsWrapper.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/client/MilvusServiceClientTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1480 Switch from OSSRH to Central Publishing Portal
  pom.xml
Labels: lgtm, approved, ci-passed, size/S

#1491 [cherry-pick] alias interface support database
  sdk-core/src/main/java/io/milvus/v2/service/utility/UtilityService.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/AlterAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/CreateAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/DescribeAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/DropAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/ListAliasesReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/response/DescribeAliasResp.java
Labels: lgtm, approved, ci-passed, size/M

#1489 alias interface support database
  sdk-core/src/main/java/io/milvus/v2/service/utility/UtilityService.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/AlterAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/CreateAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/DescribeAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/DropAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/ListAliasesReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/response/DescribeAliasResp.java
Labels: lgtm, approved, ci-passed, size/M

#1490 [cherry-pick] alias interface support database
  sdk-core/src/main/java/io/milvus/v2/service/utility/UtilityService.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/AlterAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/CreateAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/DescribeAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/DropAliasReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/request/ListAliasesReq.java
  sdk-core/src/main/java/io/milvus/v2/service/utility/response/DescribeAliasResp.java
Labels: lgtm, approved, ci-passed, size/M

#1498 [cherry-pick] Add testcases for alias interface support database.
  .github/workflows/java_sdk_ci_test.yaml
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/BaseTest.java
  tests/milvustestv2/src/main/java/com/zilliz/milvustestv2/common/CommonFunction.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/AlterAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/CreateAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/DescribeAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/DropAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/alias/ListAliasTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/bulk/GetImportProgressTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/bulk/ListImportJobsTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/collection/AddFieldTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/others/GetServerVersionTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/QueryTest.java
  tests/milvustestv2/src/test/java/com/zilliz/milvustestv2/vectorOperation/SearchTest.java
Labels: size/L, lgtm, approved, ci-passed

#1500 first step: remove lombok at io.milvus.v2.service.resourcegroup
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/CreateResourceGroupReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/DescribeResourceGroupReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/DropResourceGroupReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/ListResourceGroupsReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/TransferNodeReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/TransferReplicaReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/request/UpdateResourceGroupsReq.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/response/DescribeResourceGroupResp.java
  sdk-core/src/main/java/io/milvus/v2/service/resourcegroup/response/ListResourceGroupsResp.java
Labels: lgtm, approved, ci-passed, size/XL

#1501 cherry-pick: fix log message (#1488)
  sdk-core/src/main/java/io/milvus/client/MilvusClient.java
  sdk-core/src/main/java/io/milvus/orm/iterator/SearchIterator.java
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/PartitionService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
Labels: approved, ci-passed, size/S

#1503 Allows upsert and autoid=true for MilvusClientV1
  examples/src/main/java/io/milvus/v1/UpsertExample.java
  examples/src/main/java/io/milvus/v2/UpsertExample.java
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/InsertResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/UpsertResp.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1504 Allows upsert and autoid=true for MilvusClientV1
  examples/src/main/java/io/milvus/v1/UpsertExample.java
  examples/src/main/java/io/milvus/v2/UpsertExample.java
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/InsertResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/UpsertResp.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1505 Allows upsert and autoid=true for MilvusClientV1
  examples/src/main/java/io/milvus/v1/UpsertExample.java
  examples/src/main/java/io/milvus/v2/UpsertExample.java
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/InsertResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/UpsertResp.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed

#1506 fix log message (#1488)
  sdk-core/src/main/java/io/milvus/client/MilvusClient.java
  sdk-core/src/main/java/io/milvus/orm/iterator/SearchIterator.java
  sdk-core/src/main/java/io/milvus/v2/client/MilvusClientV2.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/PartitionService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
Labels: lgtm, approved, ci-passed, size/S

#1507 Allows upsert and autoid=true for MilvusClientV1 (#1504)
  examples/src/main/java/io/milvus/v1/UpsertExample.java
  examples/src/main/java/io/milvus/v2/UpsertExample.java
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/VectorService.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/InsertResp.java
  sdk-core/src/main/java/io/milvus/v2/service/vector/response/UpsertResp.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: size/L, lgtm, approved, ci-passed
