Repository milvus-io/milvus-sdk-java, pull requests merged in 2025-02, with the labels that each got.

#1294 Change example code path
  .gitignore
  examples/src/main/java/io/milvus/v1/ArrayFieldExample.java
  examples/src/main/java/io/milvus/v1/BinaryVectorExample.java
  examples/src/main/java/io/milvus/v1/BulkWriterExample.java
  examples/src/main/java/io/milvus/v1/ClientPoolExample.java
  examples/src/main/java/io/milvus/v1/CommonUtils.java
  examples/src/main/java/io/milvus/v1/ConsistencyLevelExample.java
  examples/src/main/java/io/milvus/v1/Float16VectorExample.java
  examples/src/main/java/io/milvus/v1/GeneralExample.java
  examples/src/main/java/io/milvus/v1/HighLevelExample.java
  examples/src/main/java/io/milvus/v1/HybridSearchExample.java
  examples/src/main/java/io/milvus/v1/IteratorExample.java
  examples/src/main/java/io/milvus/v1/JsonFieldExample.java
  examples/src/main/java/io/milvus/v1/NullAndDefaultExample.java
  examples/src/main/java/io/milvus/v1/RBACExample.java
  examples/src/main/java/io/milvus/v1/ResourceGroupExample.java
  examples/src/main/java/io/milvus/v1/SimpleExample.java
  examples/src/main/java/io/milvus/v1/SparseVectorExample.java
  examples/src/main/java/io/milvus/v1/TLSExample.java
  examples/src/main/java/io/milvus/v1/resourcegroup/NodeInfo.java
  examples/src/main/java/io/milvus/v1/resourcegroup/ResourceGroupInfo.java
  examples/src/main/java/io/milvus/v1/resourcegroup/ResourceGroupManagement.java
  examples/src/main/java/io/milvus/v2/ArrayFieldExample.java
  examples/src/main/java/io/milvus/v2/BinaryVectorExample.java
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  examples/src/main/java/io/milvus/v2/ClientPoolExample.java
  examples/src/main/java/io/milvus/v2/ConsistencyLevelExample.java
  examples/src/main/java/io/milvus/v2/Float16VectorExample.java
  examples/src/main/java/io/milvus/v2/FullTextSearchExample.java
  examples/src/main/java/io/milvus/v2/GeneralExample.java
  examples/src/main/java/io/milvus/v2/HybridSearchExample.java
  examples/src/main/java/io/milvus/v2/IteratorExample.java
  examples/src/main/java/io/milvus/v2/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/NullAndDefaultExample.java
  examples/src/main/java/io/milvus/v2/SimpleExample.java
  examples/src/main/java/io/milvus/v2/SparseVectorExample.java
  examples/src/main/java/io/milvus/v2/TLSExample.java
  examples/src/main/java/io/milvus/v2/TextMatchExample.java
  examples/src/main/resources/data/train_embeddings.csv
  examples/src/main/resources/log4j.properties
  examples/src/main/resources/tls/gen.sh
  examples/src/main/resources/tls/openssl.cnf
Labels: lgtm, approved, ci-passed, size/XS

#1295 Change example code path
  .gitignore
  examples/src/main/java/io/milvus/v1/ArrayFieldExample.java
  examples/src/main/java/io/milvus/v1/BinaryVectorExample.java
  examples/src/main/java/io/milvus/v1/BulkWriterExample.java
  examples/src/main/java/io/milvus/v1/ClientPoolExample.java
  examples/src/main/java/io/milvus/v1/CommonUtils.java
  examples/src/main/java/io/milvus/v1/ConsistencyLevelExample.java
  examples/src/main/java/io/milvus/v1/Float16VectorExample.java
  examples/src/main/java/io/milvus/v1/GeneralExample.java
  examples/src/main/java/io/milvus/v1/HighLevelExample.java
  examples/src/main/java/io/milvus/v1/HybridSearchExample.java
  examples/src/main/java/io/milvus/v1/IteratorExample.java
  examples/src/main/java/io/milvus/v1/JsonFieldExample.java
  examples/src/main/java/io/milvus/v1/NullAndDefaultExample.java
  examples/src/main/java/io/milvus/v1/RBACExample.java
  examples/src/main/java/io/milvus/v1/ResourceGroupExample.java
  examples/src/main/java/io/milvus/v1/SimpleExample.java
  examples/src/main/java/io/milvus/v1/SparseVectorExample.java
  examples/src/main/java/io/milvus/v1/TLSExample.java
  examples/src/main/java/io/milvus/v1/resourcegroup/NodeInfo.java
  examples/src/main/java/io/milvus/v1/resourcegroup/ResourceGroupInfo.java
  examples/src/main/java/io/milvus/v1/resourcegroup/ResourceGroupManagement.java
  examples/src/main/java/io/milvus/v2/ArrayFieldExample.java
  examples/src/main/java/io/milvus/v2/BinaryVectorExample.java
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  examples/src/main/java/io/milvus/v2/ClientPoolExample.java
  examples/src/main/java/io/milvus/v2/ConsistencyLevelExample.java
  examples/src/main/java/io/milvus/v2/Float16VectorExample.java
  examples/src/main/java/io/milvus/v2/FullTextSearchExample.java
  examples/src/main/java/io/milvus/v2/GeneralExample.java
  examples/src/main/java/io/milvus/v2/HybridSearchExample.java
  examples/src/main/java/io/milvus/v2/IteratorExample.java
  examples/src/main/java/io/milvus/v2/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/NullAndDefaultExample.java
  examples/src/main/java/io/milvus/v2/SimpleExample.java
  examples/src/main/java/io/milvus/v2/SparseVectorExample.java
  examples/src/main/java/io/milvus/v2/TLSExample.java
  examples/src/main/java/io/milvus/v2/TextMatchExample.java
  examples/src/main/resources/data/train_embeddings.csv
  examples/src/main/resources/log4j.properties
  examples/src/main/resources/tls/gen.sh
  examples/src/main/resources/tls/openssl.cnf
Labels: lgtm, approved, ci-passed, size/XS

#1296 Change example code path
  .gitignore
  examples/src/main/java/io/milvus/v1/ArrayFieldExample.java
  examples/src/main/java/io/milvus/v1/BinaryVectorExample.java
  examples/src/main/java/io/milvus/v1/BulkWriterExample.java
  examples/src/main/java/io/milvus/v1/ClientPoolExample.java
  examples/src/main/java/io/milvus/v1/CommonUtils.java
  examples/src/main/java/io/milvus/v1/ConsistencyLevelExample.java
  examples/src/main/java/io/milvus/v1/Float16VectorExample.java
  examples/src/main/java/io/milvus/v1/GeneralExample.java
  examples/src/main/java/io/milvus/v1/HighLevelExample.java
  examples/src/main/java/io/milvus/v1/HybridSearchExample.java
  examples/src/main/java/io/milvus/v1/IteratorExample.java
  examples/src/main/java/io/milvus/v1/JsonFieldExample.java
  examples/src/main/java/io/milvus/v1/RBACExample.java
  examples/src/main/java/io/milvus/v1/ResourceGroupExample.java
  examples/src/main/java/io/milvus/v1/SimpleExample.java
  examples/src/main/java/io/milvus/v1/SparseVectorExample.java
  examples/src/main/java/io/milvus/v1/TLSExample.java
  examples/src/main/java/io/milvus/v1/resourcegroup/NodeInfo.java
  examples/src/main/java/io/milvus/v1/resourcegroup/ResourceGroupInfo.java
  examples/src/main/java/io/milvus/v1/resourcegroup/ResourceGroupManagement.java
  examples/src/main/java/io/milvus/v2/ArrayFieldExample.java
  examples/src/main/java/io/milvus/v2/BinaryVectorExample.java
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  examples/src/main/java/io/milvus/v2/ClientPoolExample.java
  examples/src/main/java/io/milvus/v2/ConsistencyLevelExample.java
  examples/src/main/java/io/milvus/v2/Float16VectorExample.java
  examples/src/main/java/io/milvus/v2/GeneralExample.java
  examples/src/main/java/io/milvus/v2/HybridSearchExample.java
  examples/src/main/java/io/milvus/v2/IteratorExample.java
  examples/src/main/java/io/milvus/v2/JsonFieldExample.java
  examples/src/main/java/io/milvus/v2/SimpleExample.java
  examples/src/main/java/io/milvus/v2/SparseVectorExample.java
  examples/src/main/java/io/milvus/v2/TLSExample.java
  examples/src/main/resources/data/train_embeddings.csv
  examples/src/main/resources/log4j.properties
  examples/src/main/resources/tls/gen.sh
  examples/src/main/resources/tls/openssl.cnf
Labels: lgtm, approved, ci-passed, size/XS

#1300 Support HNSW_PQ/HNSW_SQ/HNSW_PRQ
  docker-compose.yml
  sdk-bulkwriter/src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
  sdk-core/src/main/java/io/milvus/param/IndexType.java
  sdk-core/src/main/java/io/milvus/v2/common/IndexParam.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1301 Support HNSW_PQ/HNSW_SQ/HNSW_PRQ
  docker-compose.yml
  sdk-bulkwriter/src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
  sdk-core/src/main/java/io/milvus/param/IndexType.java
  sdk-core/src/main/java/io/milvus/v2/common/IndexParam.java
  sdk-core/src/test/java/io/milvus/client/MilvusClientDockerTest.java
  sdk-core/src/test/java/io/milvus/v2/client/MilvusClientV2DockerTest.java
Labels: lgtm, approved, ci-passed, size/S

#1302 fix client-v2 error
  sdk-core/src/main/java/io/milvus/v2/common/DataType.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/main/java/io/milvus/v2/service/index/request/CreateIndexReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1303 [cherry-pick] fix client-v2 error
  sdk-core/src/main/java/io/milvus/v2/common/DataType.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/CollectionService.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/AddFieldReq.java
  sdk-core/src/main/java/io/milvus/v2/service/collection/request/CreateCollectionReq.java
  sdk-core/src/main/java/io/milvus/v2/service/index/IndexService.java
  sdk-core/src/main/java/io/milvus/v2/service/index/request/CreateIndexReq.java
  sdk-core/src/main/java/io/milvus/v2/utils/SchemaUtils.java
Labels: lgtm, approved, ci-passed, size/M

#1304 fix: add the err msg for the json type to avoid the null point exception
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#1305 fix:[2.5] add the err msg for the json type to avoid the null point exception
  sdk-core/src/main/java/io/milvus/param/ParamUtils.java
Labels: lgtm, approved, ci-passed, size/XS

#1306 LoadPartitions support replicas
  sdk-core/src/main/java/io/milvus/v2/service/partition/PartitionService.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/request/LoadPartitionsReq.java
Labels: lgtm, approved, ci-passed, size/XS

#1307 LoadPartitions support replicas
  sdk-core/src/main/java/io/milvus/v2/service/partition/PartitionService.java
  sdk-core/src/main/java/io/milvus/v2/service/partition/request/LoadPartitionsReq.java
Labels: lgtm, approved, ci-passed, size/XS

#1308 optim bulkWriter to reduce memory usage
  examples/src/main/java/io/milvus/v1/BulkWriterExample.java
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/Buffer.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/BulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/LocalBulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/LocalBulkWriterParam.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/RemoteBulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/RemoteBulkWriterParam.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/CSVFileWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/FormatFileWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/JSONFileWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/ParquetFileWriter.java
  sdk-bulkwriter/src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
Labels: lgtm, size/XXL, approved, ci-passed

#1309 [cherry-pick] optim bulkWriter to reduce memory usage
  examples/src/main/java/io/milvus/v1/BulkWriterExample.java
  examples/src/main/java/io/milvus/v2/BulkWriterExample.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/Buffer.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/BulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/LocalBulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/LocalBulkWriterParam.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/RemoteBulkWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/RemoteBulkWriterParam.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/CSVFileWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/FormatFileWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/JSONFileWriter.java
  sdk-bulkwriter/src/main/java/io/milvus/bulkwriter/writer/ParquetFileWriter.java
  sdk-bulkwriter/src/test/java/io/milvus/bulkwriter/BulkWriterTest.java
Labels: lgtm, size/XXL, approved, ci-passed
